--!nonstrict
-- Generated by tools/bindgen.py from raylib 6.0. Do not edit.
-- Point your editor at it: luau-lsp --definitions=types/raylib.d.lua

declare extern type Vector4 with
    x: number
    y: number
    z: number
    w: number
end

declare extern type Matrix with
    m0: number
    m4: number
    m8: number
    m12: number
    m1: number
    m5: number
    m9: number
    m13: number
    m2: number
    m6: number
    m10: number
    m14: number
    m3: number
    m7: number
    m11: number
    m15: number
end

declare extern type Rectangle with
    x: number
    y: number
    width: number
    height: number
end

declare extern type Image with
    width: number
    height: number
    mipmaps: number
    format: number
end

declare extern type Texture with
    id: number
    width: number
    height: number
    mipmaps: number
    format: number
end

declare extern type RenderTexture with
    id: number
    texture: Texture
    depth: Texture
end

declare extern type NPatchInfo with
    source: Rectangle
    left: number
    top: number
    right: number
    bottom: number
    layout: number
end

declare extern type GlyphInfo with
    value: number
    offsetX: number
    offsetY: number
    advanceX: number
end

declare extern type Font with
    baseSize: number
    glyphCount: number
    glyphPadding: number
    texture: Texture
end

declare extern type Camera3D with
    position: vector
    target: vector
    up: vector
    fovy: number
    projection: number
end

declare extern type Camera2D with
    offset: vector
    target: vector
    rotation: number
    zoom: number
end

declare extern type Mesh with
    vertexCount: number
    triangleCount: number
    boneCount: number
    vaoId: number
end

declare extern type Shader with
    id: number
end

declare extern type MaterialMap with
    texture: Texture
    color: number
    value: number
end

declare extern type Material with
end

declare extern type Transform with
    translation: vector
    rotation: Vector4
    scale: vector
end

declare extern type BoneInfo with
    parent: number
end

declare extern type ModelSkeleton with
    boneCount: number
end

declare extern type Model with
    transform: Matrix
    meshCount: number
    materialCount: number
end

declare extern type ModelAnimation with
    boneCount: number
    keyframeCount: number
end

declare extern type Ray with
    position: vector
    direction: vector
end

declare extern type RayCollision with
    hit: boolean
    distance: number
    point: vector
    normal: vector
end

declare extern type BoundingBox with
    min: vector
    max: vector
end

declare extern type Wave with
    frameCount: number
    sampleRate: number
    sampleSize: number
    channels: number
end

declare extern type AudioStream with
    sampleRate: number
    sampleSize: number
    channels: number
end

declare extern type Sound with
    frameCount: number
end

declare extern type Music with
    frameCount: number
    looping: boolean
    ctxType: number
end

declare extern type VrDeviceInfo with
    hResolution: number
    vResolution: number
    hScreenSize: number
    vScreenSize: number
    eyeToScreenDistance: number
    lensSeparationDistance: number
    interpupillaryDistance: number
end

declare extern type VrStereoConfig with
end

declare extern type FilePathList with
    count: number
end

declare extern type AutomationEvent with
    frame: number
    type: number
end

declare extern type AutomationEventList with
    capacity: number
    count: number
end

export type Quaternion = Vector4
export type Texture2D = Texture
export type TextureCubemap = Texture
export type RenderTexture2D = RenderTexture
export type Camera = Camera3D

declare DEV: boolean

declare raylib: {
    InitWindow: (width: number, height: number, title: string) -> (),
    CloseWindow: () -> (),
    WindowShouldClose: () -> boolean,
    IsWindowReady: () -> boolean,
    IsWindowFullscreen: () -> boolean,
    IsWindowHidden: () -> boolean,
    IsWindowMinimized: () -> boolean,
    IsWindowMaximized: () -> boolean,
    IsWindowFocused: () -> boolean,
    IsWindowResized: () -> boolean,
    IsWindowState: (flag: number) -> boolean,
    SetWindowState: (flags: number) -> (),
    ClearWindowState: (flags: number) -> (),
    ToggleFullscreen: () -> (),
    ToggleBorderlessWindowed: () -> (),
    MaximizeWindow: () -> (),
    MinimizeWindow: () -> (),
    RestoreWindow: () -> (),
    SetWindowIcon: (image: Image) -> (),
    SetWindowTitle: (title: string) -> (),
    SetWindowPosition: (x: number, y: number) -> (),
    SetWindowMonitor: (monitor: number) -> (),
    SetWindowMinSize: (width: number, height: number) -> (),
    SetWindowMaxSize: (width: number, height: number) -> (),
    SetWindowSize: (width: number, height: number) -> (),
    SetWindowOpacity: (opacity: number) -> (),
    SetWindowFocused: () -> (),
    GetScreenWidth: () -> number,
    GetScreenHeight: () -> number,
    GetRenderWidth: () -> number,
    GetRenderHeight: () -> number,
    GetMonitorCount: () -> number,
    GetCurrentMonitor: () -> number,
    GetMonitorPosition: (monitor: number) -> vector,
    GetMonitorWidth: (monitor: number) -> number,
    GetMonitorHeight: (monitor: number) -> number,
    GetMonitorPhysicalWidth: (monitor: number) -> number,
    GetMonitorPhysicalHeight: (monitor: number) -> number,
    GetMonitorRefreshRate: (monitor: number) -> number,
    GetWindowPosition: () -> vector,
    GetWindowScaleDPI: () -> vector,
    GetMonitorName: (monitor: number) -> string,
    SetClipboardText: (text: string) -> (),
    GetClipboardText: () -> string,
    GetClipboardImage: () -> Image,
    EnableEventWaiting: () -> (),
    DisableEventWaiting: () -> (),
    ShowCursor: () -> (),
    HideCursor: () -> (),
    IsCursorHidden: () -> boolean,
    EnableCursor: () -> (),
    DisableCursor: () -> (),
    IsCursorOnScreen: () -> boolean,
    ClearBackground: (color: number) -> (),
    BeginDrawing: () -> (),
    EndDrawing: () -> (),
    BeginMode2D: (camera: Camera2D) -> (),
    EndMode2D: () -> (),
    BeginMode3D: (camera: Camera3D) -> (),
    EndMode3D: () -> (),
    BeginTextureMode: (target: RenderTexture) -> (),
    EndTextureMode: () -> (),
    BeginShaderMode: (shader: Shader) -> (),
    EndShaderMode: () -> (),
    BeginBlendMode: (mode: number) -> (),
    EndBlendMode: () -> (),
    BeginScissorMode: (x: number, y: number, width: number, height: number) -> (),
    EndScissorMode: () -> (),
    BeginVrStereoMode: (config: VrStereoConfig) -> (),
    EndVrStereoMode: () -> (),
    LoadVrStereoConfig: (device: VrDeviceInfo) -> VrStereoConfig,
    UnloadVrStereoConfig: (config: VrStereoConfig) -> (),
    LoadShader: (vsFileName: string, fsFileName: string) -> Shader,
    LoadShaderFromMemory: (vsCode: string, fsCode: string) -> Shader,
    IsShaderValid: (shader: Shader) -> boolean,
    GetShaderLocation: (shader: Shader, uniformName: string) -> number,
    GetShaderLocationAttrib: (shader: Shader, attribName: string) -> number,
    SetShaderValueMatrix: (shader: Shader, locIndex: number, mat: Matrix) -> (),
    SetShaderValueTexture: (shader: Shader, locIndex: number, texture: Texture) -> (),
    UnloadShader: (shader: Shader) -> (),
    GetScreenToWorldRay: (position: vector, camera: Camera3D) -> Ray,
    GetScreenToWorldRayEx: (position: vector, camera: Camera3D, width: number, height: number) -> Ray,
    GetWorldToScreen: (position: vector, camera: Camera3D) -> vector,
    GetWorldToScreenEx: (position: vector, camera: Camera3D, width: number, height: number) -> vector,
    GetWorldToScreen2D: (position: vector, camera: Camera2D) -> vector,
    GetScreenToWorld2D: (position: vector, camera: Camera2D) -> vector,
    GetCameraMatrix: (camera: Camera3D) -> Matrix,
    GetCameraMatrix2D: (camera: Camera2D) -> Matrix,
    SetTargetFPS: (fps: number) -> (),
    GetFrameTime: () -> number,
    GetTime: () -> number,
    GetFPS: () -> number,
    SwapScreenBuffer: () -> (),
    PollInputEvents: () -> (),
    WaitTime: (seconds: number) -> (),
    SetRandomSeed: (seed: number) -> (),
    GetRandomValue: (min: number, max: number) -> number,
    TakeScreenshot: (fileName: string) -> (),
    SetConfigFlags: (flags: number) -> (),
    OpenURL: (url: string) -> (),
    SetTraceLogLevel: (logLevel: number) -> (),
    SaveFileText: (fileName: string, text: string) -> boolean,
    FileRename: (fileName: string, fileRename: string) -> number,
    FileRemove: (fileName: string) -> number,
    FileCopy: (srcPath: string, dstPath: string) -> number,
    FileMove: (srcPath: string, dstPath: string) -> number,
    FileTextReplace: (fileName: string, search: string, replacement: string) -> number,
    FileTextFindIndex: (fileName: string, search: string) -> number,
    FileExists: (fileName: string) -> boolean,
    DirectoryExists: (dirPath: string) -> boolean,
    IsFileExtension: (fileName: string, ext: string) -> boolean,
    GetFileLength: (fileName: string) -> number,
    GetFileModTime: (fileName: string) -> number,
    GetFileExtension: (fileName: string) -> string,
    GetFileName: (filePath: string) -> string,
    GetFileNameWithoutExt: (filePath: string) -> string,
    GetDirectoryPath: (filePath: string) -> string,
    GetPrevDirectoryPath: (dirPath: string) -> string,
    GetWorkingDirectory: () -> string,
    GetApplicationDirectory: () -> string,
    MakeDirectory: (dirPath: string) -> number,
    ChangeDirectory: (dirPath: string) -> boolean,
    IsPathFile: (path: string) -> boolean,
    IsFileNameValid: (fileName: string) -> boolean,
    LoadDirectoryFiles: (dirPath: string) -> FilePathList,
    LoadDirectoryFilesEx: (basePath: string, filter: string, scanSubdirs: boolean) -> FilePathList,
    UnloadDirectoryFiles: (files: FilePathList) -> (),
    IsFileDropped: () -> boolean,
    LoadDroppedFiles: () -> FilePathList,
    UnloadDroppedFiles: (files: FilePathList) -> (),
    GetDirectoryFileCount: (dirPath: string) -> number,
    GetDirectoryFileCountEx: (basePath: string, filter: string, scanSubdirs: boolean) -> number,
    LoadAutomationEventList: (fileName: string) -> AutomationEventList,
    UnloadAutomationEventList: (list: AutomationEventList) -> (),
    ExportAutomationEventList: (list: AutomationEventList, fileName: string) -> boolean,
    SetAutomationEventBaseFrame: (frame: number) -> (),
    StartAutomationEventRecording: () -> (),
    StopAutomationEventRecording: () -> (),
    PlayAutomationEvent: (event: AutomationEvent) -> (),
    IsKeyPressed: (key: number) -> boolean,
    IsKeyPressedRepeat: (key: number) -> boolean,
    IsKeyDown: (key: number) -> boolean,
    IsKeyReleased: (key: number) -> boolean,
    IsKeyUp: (key: number) -> boolean,
    GetKeyPressed: () -> number,
    GetCharPressed: () -> number,
    GetKeyName: (key: number) -> string,
    SetExitKey: (key: number) -> (),
    IsGamepadAvailable: (gamepad: number) -> boolean,
    GetGamepadName: (gamepad: number) -> string,
    IsGamepadButtonPressed: (gamepad: number, button: number) -> boolean,
    IsGamepadButtonDown: (gamepad: number, button: number) -> boolean,
    IsGamepadButtonReleased: (gamepad: number, button: number) -> boolean,
    IsGamepadButtonUp: (gamepad: number, button: number) -> boolean,
    GetGamepadButtonPressed: () -> number,
    GetGamepadAxisCount: (gamepad: number) -> number,
    GetGamepadAxisMovement: (gamepad: number, axis: number) -> number,
    SetGamepadMappings: (mappings: string) -> number,
    SetGamepadVibration: (gamepad: number, leftMotor: number, rightMotor: number, duration: number) -> (),
    IsMouseButtonPressed: (button: number) -> boolean,
    IsMouseButtonDown: (button: number) -> boolean,
    IsMouseButtonReleased: (button: number) -> boolean,
    IsMouseButtonUp: (button: number) -> boolean,
    GetMouseX: () -> number,
    GetMouseY: () -> number,
    GetMousePosition: () -> vector,
    GetMouseDelta: () -> vector,
    SetMousePosition: (x: number, y: number) -> (),
    SetMouseOffset: (offsetX: number, offsetY: number) -> (),
    SetMouseScale: (scaleX: number, scaleY: number) -> (),
    GetMouseWheelMove: () -> number,
    GetMouseWheelMoveV: () -> vector,
    SetMouseCursor: (cursor: number) -> (),
    GetTouchX: () -> number,
    GetTouchY: () -> number,
    GetTouchPosition: (index: number) -> vector,
    GetTouchPointId: (index: number) -> number,
    GetTouchPointCount: () -> number,
    SetGesturesEnabled: (flags: number) -> (),
    IsGestureDetected: (gesture: number) -> boolean,
    GetGestureDetected: () -> number,
    GetGestureHoldDuration: () -> number,
    GetGestureDragVector: () -> vector,
    GetGestureDragAngle: () -> number,
    GetGesturePinchVector: () -> vector,
    GetGesturePinchAngle: () -> number,
    UpdateCamera: (camera: Camera3D, mode: number) -> (),
    UpdateCameraPro: (camera: Camera3D, movement: vector, rotation: vector, zoom: number) -> (),
    SetShapesTexture: (texture: Texture, source: Rectangle) -> (),
    GetShapesTexture: () -> Texture,
    GetShapesTextureRectangle: () -> Rectangle,
    DrawPixel: (posX: number, posY: number, color: number) -> (),
    DrawPixelV: (position: vector, color: number) -> (),
    DrawLine: (startPosX: number, startPosY: number, endPosX: number, endPosY: number, color: number) -> (),
    DrawLineV: (startPos: vector, endPos: vector, color: number) -> (),
    DrawLineEx: (startPos: vector, endPos: vector, thick: number, color: number) -> (),
    DrawLineBezier: (startPos: vector, endPos: vector, thick: number, color: number) -> (),
    DrawLineDashed: (startPos: vector, endPos: vector, dashSize: number, spaceSize: number, color: number) -> (),
    DrawCircle: (centerX: number, centerY: number, radius: number, color: number) -> (),
    DrawCircleV: (center: vector, radius: number, color: number) -> (),
    DrawCircleGradient: (center: vector, radius: number, inner: number, outer: number) -> (),
    DrawCircleSector: (center: vector, radius: number, startAngle: number, endAngle: number, segments: number, color: number) -> (),
    DrawCircleSectorLines: (center: vector, radius: number, startAngle: number, endAngle: number, segments: number, color: number) -> (),
    DrawCircleLines: (centerX: number, centerY: number, radius: number, color: number) -> (),
    DrawCircleLinesV: (center: vector, radius: number, color: number) -> (),
    DrawEllipse: (centerX: number, centerY: number, radiusH: number, radiusV: number, color: number) -> (),
    DrawEllipseV: (center: vector, radiusH: number, radiusV: number, color: number) -> (),
    DrawEllipseLines: (centerX: number, centerY: number, radiusH: number, radiusV: number, color: number) -> (),
    DrawEllipseLinesV: (center: vector, radiusH: number, radiusV: number, color: number) -> (),
    DrawRing: (center: vector, innerRadius: number, outerRadius: number, startAngle: number, endAngle: number, segments: number, color: number) -> (),
    DrawRingLines: (center: vector, innerRadius: number, outerRadius: number, startAngle: number, endAngle: number, segments: number, color: number) -> (),
    DrawRectangle: (posX: number, posY: number, width: number, height: number, color: number) -> (),
    DrawRectangleV: (position: vector, size: vector, color: number) -> (),
    DrawRectangleRec: (rec: Rectangle, color: number) -> (),
    DrawRectanglePro: (rec: Rectangle, origin: vector, rotation: number, color: number) -> (),
    DrawRectangleGradientV: (posX: number, posY: number, width: number, height: number, top: number, bottom: number) -> (),
    DrawRectangleGradientH: (posX: number, posY: number, width: number, height: number, left: number, right: number) -> (),
    DrawRectangleGradientEx: (rec: Rectangle, topLeft: number, bottomLeft: number, bottomRight: number, topRight: number) -> (),
    DrawRectangleLines: (posX: number, posY: number, width: number, height: number, color: number) -> (),
    DrawRectangleLinesEx: (rec: Rectangle, lineThick: number, color: number) -> (),
    DrawRectangleRounded: (rec: Rectangle, roundness: number, segments: number, color: number) -> (),
    DrawRectangleRoundedLines: (rec: Rectangle, roundness: number, segments: number, color: number) -> (),
    DrawRectangleRoundedLinesEx: (rec: Rectangle, roundness: number, segments: number, lineThick: number, color: number) -> (),
    DrawTriangle: (v1: vector, v2: vector, v3: vector, color: number) -> (),
    DrawTriangleLines: (v1: vector, v2: vector, v3: vector, color: number) -> (),
    DrawPoly: (center: vector, sides: number, radius: number, rotation: number, color: number) -> (),
    DrawPolyLines: (center: vector, sides: number, radius: number, rotation: number, color: number) -> (),
    DrawPolyLinesEx: (center: vector, sides: number, radius: number, rotation: number, lineThick: number, color: number) -> (),
    DrawSplineSegmentLinear: (p1: vector, p2: vector, thick: number, color: number) -> (),
    DrawSplineSegmentBasis: (p1: vector, p2: vector, p3: vector, p4: vector, thick: number, color: number) -> (),
    DrawSplineSegmentCatmullRom: (p1: vector, p2: vector, p3: vector, p4: vector, thick: number, color: number) -> (),
    DrawSplineSegmentBezierQuadratic: (p1: vector, c2: vector, p3: vector, thick: number, color: number) -> (),
    DrawSplineSegmentBezierCubic: (p1: vector, c2: vector, c3: vector, p4: vector, thick: number, color: number) -> (),
    GetSplinePointLinear: (startPos: vector, endPos: vector, t: number) -> vector,
    GetSplinePointBasis: (p1: vector, p2: vector, p3: vector, p4: vector, t: number) -> vector,
    GetSplinePointCatmullRom: (p1: vector, p2: vector, p3: vector, p4: vector, t: number) -> vector,
    GetSplinePointBezierQuad: (p1: vector, c2: vector, p3: vector, t: number) -> vector,
    GetSplinePointBezierCubic: (p1: vector, c2: vector, c3: vector, p4: vector, t: number) -> vector,
    CheckCollisionRecs: (rec1: Rectangle, rec2: Rectangle) -> boolean,
    CheckCollisionCircles: (center1: vector, radius1: number, center2: vector, radius2: number) -> boolean,
    CheckCollisionCircleRec: (center: vector, radius: number, rec: Rectangle) -> boolean,
    CheckCollisionCircleLine: (center: vector, radius: number, p1: vector, p2: vector) -> boolean,
    CheckCollisionPointRec: (point: vector, rec: Rectangle) -> boolean,
    CheckCollisionPointCircle: (point: vector, center: vector, radius: number) -> boolean,
    CheckCollisionPointTriangle: (point: vector, p1: vector, p2: vector, p3: vector) -> boolean,
    CheckCollisionPointLine: (point: vector, p1: vector, p2: vector, threshold: number) -> boolean,
    GetCollisionRec: (rec1: Rectangle, rec2: Rectangle) -> Rectangle,
    LoadImage: (fileName: string) -> Image,
    LoadImageRaw: (fileName: string, width: number, height: number, format: number, headerSize: number) -> Image,
    LoadImageFromTexture: (texture: Texture) -> Image,
    LoadImageFromScreen: () -> Image,
    IsImageValid: (image: Image) -> boolean,
    UnloadImage: (image: Image) -> (),
    ExportImage: (image: Image, fileName: string) -> boolean,
    ExportImageAsCode: (image: Image, fileName: string) -> boolean,
    GenImageColor: (width: number, height: number, color: number) -> Image,
    GenImageGradientLinear: (width: number, height: number, direction: number, start: number, end_: number) -> Image,
    GenImageGradientRadial: (width: number, height: number, density: number, inner: number, outer: number) -> Image,
    GenImageGradientSquare: (width: number, height: number, density: number, inner: number, outer: number) -> Image,
    GenImageChecked: (width: number, height: number, checksX: number, checksY: number, col1: number, col2: number) -> Image,
    GenImageWhiteNoise: (width: number, height: number, factor: number) -> Image,
    GenImagePerlinNoise: (width: number, height: number, offsetX: number, offsetY: number, scale: number) -> Image,
    GenImageCellular: (width: number, height: number, tileSize: number) -> Image,
    GenImageText: (width: number, height: number, text: string) -> Image,
    ImageCopy: (image: Image) -> Image,
    ImageFromImage: (image: Image, rec: Rectangle) -> Image,
    ImageFromChannel: (image: Image, selectedChannel: number) -> Image,
    ImageText: (text: string, fontSize: number, color: number) -> Image,
    ImageTextEx: (font: Font, text: string, fontSize: number, spacing: number, tint: number) -> Image,
    ImageFormat: (image: Image, newFormat: number) -> (),
    ImageToPOT: (image: Image, fill: number) -> (),
    ImageCrop: (image: Image, crop: Rectangle) -> (),
    ImageAlphaCrop: (image: Image, threshold: number) -> (),
    ImageAlphaClear: (image: Image, color: number, threshold: number) -> (),
    ImageAlphaMask: (image: Image, alphaMask: Image) -> (),
    ImageAlphaPremultiply: (image: Image) -> (),
    ImageBlurGaussian: (image: Image, blurSize: number) -> (),
    ImageResize: (image: Image, newWidth: number, newHeight: number) -> (),
    ImageResizeNN: (image: Image, newWidth: number, newHeight: number) -> (),
    ImageResizeCanvas: (image: Image, newWidth: number, newHeight: number, offsetX: number, offsetY: number, fill: number) -> (),
    ImageMipmaps: (image: Image) -> (),
    ImageDither: (image: Image, rBpp: number, gBpp: number, bBpp: number, aBpp: number) -> (),
    ImageFlipVertical: (image: Image) -> (),
    ImageFlipHorizontal: (image: Image) -> (),
    ImageRotate: (image: Image, degrees: number) -> (),
    ImageRotateCW: (image: Image) -> (),
    ImageRotateCCW: (image: Image) -> (),
    ImageColorTint: (image: Image, color: number) -> (),
    ImageColorInvert: (image: Image) -> (),
    ImageColorGrayscale: (image: Image) -> (),
    ImageColorContrast: (image: Image, contrast: number) -> (),
    ImageColorBrightness: (image: Image, brightness: number) -> (),
    ImageColorReplace: (image: Image, color: number, replace: number) -> (),
    GetImageAlphaBorder: (image: Image, threshold: number) -> Rectangle,
    GetImageColor: (image: Image, x: number, y: number) -> number,
    ImageClearBackground: (dst: Image, color: number) -> (),
    ImageDrawPixel: (dst: Image, posX: number, posY: number, color: number) -> (),
    ImageDrawPixelV: (dst: Image, position: vector, color: number) -> (),
    ImageDrawLine: (dst: Image, startPosX: number, startPosY: number, endPosX: number, endPosY: number, color: number) -> (),
    ImageDrawLineV: (dst: Image, start: vector, end_: vector, color: number) -> (),
    ImageDrawLineEx: (dst: Image, start: vector, end_: vector, thick: number, color: number) -> (),
    ImageDrawCircle: (dst: Image, centerX: number, centerY: number, radius: number, color: number) -> (),
    ImageDrawCircleV: (dst: Image, center: vector, radius: number, color: number) -> (),
    ImageDrawCircleLines: (dst: Image, centerX: number, centerY: number, radius: number, color: number) -> (),
    ImageDrawCircleLinesV: (dst: Image, center: vector, radius: number, color: number) -> (),
    ImageDrawRectangle: (dst: Image, posX: number, posY: number, width: number, height: number, color: number) -> (),
    ImageDrawRectangleV: (dst: Image, position: vector, size: vector, color: number) -> (),
    ImageDrawRectangleRec: (dst: Image, rec: Rectangle, color: number) -> (),
    ImageDrawRectangleLines: (dst: Image, rec: Rectangle, thick: number, color: number) -> (),
    ImageDrawTriangle: (dst: Image, v1: vector, v2: vector, v3: vector, color: number) -> (),
    ImageDrawTriangleEx: (dst: Image, v1: vector, v2: vector, v3: vector, c1: number, c2: number, c3: number) -> (),
    ImageDrawTriangleLines: (dst: Image, v1: vector, v2: vector, v3: vector, color: number) -> (),
    ImageDraw: (dst: Image, src: Image, srcRec: Rectangle, dstRec: Rectangle, tint: number) -> (),
    ImageDrawText: (dst: Image, text: string, posX: number, posY: number, fontSize: number, color: number) -> (),
    ImageDrawTextEx: (dst: Image, font: Font, text: string, position: vector, fontSize: number, spacing: number, tint: number) -> (),
    LoadTexture: (fileName: string) -> Texture,
    LoadTextureFromImage: (image: Image) -> Texture,
    LoadTextureCubemap: (image: Image, layout: number) -> Texture,
    LoadRenderTexture: (width: number, height: number) -> RenderTexture,
    IsTextureValid: (texture: Texture) -> boolean,
    UnloadTexture: (texture: Texture) -> (),
    IsRenderTextureValid: (target: RenderTexture) -> boolean,
    UnloadRenderTexture: (target: RenderTexture) -> (),
    GenTextureMipmaps: (texture: Texture) -> (),
    SetTextureFilter: (texture: Texture, filter: number) -> (),
    SetTextureWrap: (texture: Texture, wrap: number) -> (),
    DrawTexture: (texture: Texture, posX: number, posY: number, tint: number) -> (),
    DrawTextureV: (texture: Texture, position: vector, tint: number) -> (),
    DrawTextureEx: (texture: Texture, position: vector, rotation: number, scale: number, tint: number) -> (),
    DrawTextureRec: (texture: Texture, source: Rectangle, position: vector, tint: number) -> (),
    DrawTexturePro: (texture: Texture, source: Rectangle, dest: Rectangle, origin: vector, rotation: number, tint: number) -> (),
    DrawTextureNPatch: (texture: Texture, nPatchInfo: NPatchInfo, dest: Rectangle, origin: vector, rotation: number, tint: number) -> (),
    ColorIsEqual: (col1: number, col2: number) -> boolean,
    Fade: (color: number, alpha: number) -> number,
    ColorToInt: (color: number) -> number,
    ColorNormalize: (color: number) -> Vector4,
    ColorFromNormalized: (normalized: Vector4) -> number,
    ColorToHSV: (color: number) -> vector,
    ColorFromHSV: (hue: number, saturation: number, value: number) -> number,
    ColorTint: (color: number, tint: number) -> number,
    ColorBrightness: (color: number, factor: number) -> number,
    ColorContrast: (color: number, contrast: number) -> number,
    ColorAlpha: (color: number, alpha: number) -> number,
    ColorAlphaBlend: (dst: number, src: number, tint: number) -> number,
    ColorLerp: (color1: number, color2: number, factor: number) -> number,
    GetColor: (hexValue: number) -> number,
    GetPixelDataSize: (width: number, height: number, format: number) -> number,
    GetFontDefault: () -> Font,
    LoadFont: (fileName: string) -> Font,
    LoadFontFromImage: (image: Image, key: number, firstChar: number) -> Font,
    IsFontValid: (font: Font) -> boolean,
    UnloadFont: (font: Font) -> (),
    ExportFontAsCode: (font: Font, fileName: string) -> boolean,
    DrawFPS: (posX: number, posY: number) -> (),
    DrawText: (text: string, posX: number, posY: number, fontSize: number, color: number) -> (),
    DrawTextEx: (font: Font, text: string, position: vector, fontSize: number, spacing: number, tint: number) -> (),
    DrawTextPro: (font: Font, text: string, position: vector, origin: vector, rotation: number, fontSize: number, spacing: number, tint: number) -> (),
    DrawTextCodepoint: (font: Font, codepoint: number, position: vector, fontSize: number, tint: number) -> (),
    SetTextLineSpacing: (spacing: number) -> (),
    MeasureText: (text: string, fontSize: number) -> number,
    MeasureTextEx: (font: Font, text: string, fontSize: number, spacing: number) -> vector,
    GetGlyphIndex: (font: Font, codepoint: number) -> number,
    GetGlyphInfo: (font: Font, codepoint: number) -> GlyphInfo,
    GetGlyphAtlasRec: (font: Font, codepoint: number) -> Rectangle,
    GetCodepointCount: (text: string) -> number,
    TextIsEqual: (text1: string, text2: string) -> boolean,
    TextLength: (text: string) -> number,
    TextSubtext: (text: string, position: number, length: number) -> string,
    TextRemoveSpaces: (text: string) -> string,
    TextFindIndex: (text: string, search: string) -> number,
    TextToInteger: (text: string) -> number,
    TextToFloat: (text: string) -> number,
    DrawLine3D: (startPos: vector, endPos: vector, color: number) -> (),
    DrawPoint3D: (position: vector, color: number) -> (),
    DrawCircle3D: (center: vector, radius: number, rotationAxis: vector, rotationAngle: number, color: number) -> (),
    DrawTriangle3D: (v1: vector, v2: vector, v3: vector, color: number) -> (),
    DrawCube: (position: vector, width: number, height: number, length: number, color: number) -> (),
    DrawCubeV: (position: vector, size: vector, color: number) -> (),
    DrawCubeWires: (position: vector, width: number, height: number, length: number, color: number) -> (),
    DrawCubeWiresV: (position: vector, size: vector, color: number) -> (),
    DrawSphere: (centerPos: vector, radius: number, color: number) -> (),
    DrawSphereEx: (centerPos: vector, radius: number, rings: number, slices: number, color: number) -> (),
    DrawSphereWires: (centerPos: vector, radius: number, rings: number, slices: number, color: number) -> (),
    DrawCylinder: (position: vector, radiusTop: number, radiusBottom: number, height: number, slices: number, color: number) -> (),
    DrawCylinderEx: (startPos: vector, endPos: vector, startRadius: number, endRadius: number, sides: number, color: number) -> (),
    DrawCylinderWires: (position: vector, radiusTop: number, radiusBottom: number, height: number, slices: number, color: number) -> (),
    DrawCylinderWiresEx: (startPos: vector, endPos: vector, startRadius: number, endRadius: number, sides: number, color: number) -> (),
    DrawCapsule: (startPos: vector, endPos: vector, radius: number, slices: number, rings: number, color: number) -> (),
    DrawCapsuleWires: (startPos: vector, endPos: vector, radius: number, slices: number, rings: number, color: number) -> (),
    DrawPlane: (centerPos: vector, size: vector, color: number) -> (),
    DrawRay: (ray: Ray, color: number) -> (),
    DrawGrid: (slices: number, spacing: number) -> (),
    LoadModel: (fileName: string) -> Model,
    IsModelValid: (model: Model) -> boolean,
    UnloadModel: (model: Model) -> (),
    GetModelBoundingBox: (model: Model) -> BoundingBox,
    DrawModel: (model: Model, position: vector, scale: number, tint: number) -> (),
    DrawModelEx: (model: Model, position: vector, rotationAxis: vector, rotationAngle: number, scale: vector, tint: number) -> (),
    DrawModelWires: (model: Model, position: vector, scale: number, tint: number) -> (),
    DrawModelWiresEx: (model: Model, position: vector, rotationAxis: vector, rotationAngle: number, scale: vector, tint: number) -> (),
    DrawBoundingBox: (box: BoundingBox, color: number) -> (),
    DrawBillboard: (camera: Camera3D, texture: Texture, position: vector, scale: number, tint: number) -> (),
    DrawBillboardRec: (camera: Camera3D, texture: Texture, source: Rectangle, position: vector, size: vector, tint: number) -> (),
    DrawBillboardPro: (camera: Camera3D, texture: Texture, source: Rectangle, position: vector, up: vector, size: vector, origin: vector, rotation: number, tint: number) -> (),
    UploadMesh: (mesh: Mesh, dynamic: boolean) -> (),
    UnloadMesh: (mesh: Mesh) -> (),
    DrawMesh: (mesh: Mesh, material: Material, transform: Matrix) -> (),
    GetMeshBoundingBox: (mesh: Mesh) -> BoundingBox,
    GenMeshTangents: (mesh: Mesh) -> (),
    ExportMesh: (mesh: Mesh, fileName: string) -> boolean,
    ExportMeshAsCode: (mesh: Mesh, fileName: string) -> boolean,
    GenMeshPoly: (sides: number, radius: number) -> Mesh,
    GenMeshPlane: (width: number, length: number, resX: number, resZ: number) -> Mesh,
    GenMeshCube: (width: number, height: number, length: number) -> Mesh,
    GenMeshSphere: (radius: number, rings: number, slices: number) -> Mesh,
    GenMeshHemiSphere: (radius: number, rings: number, slices: number) -> Mesh,
    GenMeshCylinder: (radius: number, height: number, slices: number) -> Mesh,
    GenMeshCone: (radius: number, height: number, slices: number) -> Mesh,
    GenMeshTorus: (radius: number, size: number, radSeg: number, sides: number) -> Mesh,
    GenMeshKnot: (radius: number, size: number, radSeg: number, sides: number) -> Mesh,
    GenMeshHeightmap: (heightmap: Image, size: vector) -> Mesh,
    GenMeshCubicmap: (cubicmap: Image, cubeSize: vector) -> Mesh,
    LoadMaterialDefault: () -> Material,
    IsMaterialValid: (material: Material) -> boolean,
    UnloadMaterial: (material: Material) -> (),
    SetMaterialTexture: (material: Material, mapType: number, texture: Texture) -> (),
    SetModelMeshMaterial: (model: Model, meshId: number, materialId: number) -> (),
    UpdateModelAnimation: (model: Model, anim: ModelAnimation, frame: number) -> (),
    UpdateModelAnimationEx: (model: Model, animA: ModelAnimation, frameA: number, animB: ModelAnimation, frameB: number, blend: number) -> (),
    IsModelAnimationValid: (model: Model, anim: ModelAnimation) -> boolean,
    CheckCollisionSpheres: (center1: vector, radius1: number, center2: vector, radius2: number) -> boolean,
    CheckCollisionBoxes: (box1: BoundingBox, box2: BoundingBox) -> boolean,
    CheckCollisionBoxSphere: (box: BoundingBox, center: vector, radius: number) -> boolean,
    GetRayCollisionSphere: (ray: Ray, center: vector, radius: number) -> RayCollision,
    GetRayCollisionBox: (ray: Ray, box: BoundingBox) -> RayCollision,
    GetRayCollisionMesh: (ray: Ray, mesh: Mesh, transform: Matrix) -> RayCollision,
    GetRayCollisionTriangle: (ray: Ray, p1: vector, p2: vector, p3: vector) -> RayCollision,
    GetRayCollisionQuad: (ray: Ray, p1: vector, p2: vector, p3: vector, p4: vector) -> RayCollision,
    InitAudioDevice: () -> (),
    CloseAudioDevice: () -> (),
    IsAudioDeviceReady: () -> boolean,
    SetMasterVolume: (volume: number) -> (),
    GetMasterVolume: () -> number,
    LoadWave: (fileName: string) -> Wave,
    IsWaveValid: (wave: Wave) -> boolean,
    LoadSound: (fileName: string) -> Sound,
    LoadSoundFromWave: (wave: Wave) -> Sound,
    IsSoundValid: (sound: Sound) -> boolean,
    UnloadWave: (wave: Wave) -> (),
    UnloadSound: (sound: Sound) -> (),
    ExportWave: (wave: Wave, fileName: string) -> boolean,
    ExportWaveAsCode: (wave: Wave, fileName: string) -> boolean,
    PlaySound: (sound: Sound) -> (),
    StopSound: (sound: Sound) -> (),
    PauseSound: (sound: Sound) -> (),
    ResumeSound: (sound: Sound) -> (),
    IsSoundPlaying: (sound: Sound) -> boolean,
    SetSoundVolume: (sound: Sound, volume: number) -> (),
    SetSoundPitch: (sound: Sound, pitch: number) -> (),
    SetSoundPan: (sound: Sound, pan: number) -> (),
    WaveCopy: (wave: Wave) -> Wave,
    WaveCrop: (wave: Wave, initFrame: number, finalFrame: number) -> (),
    WaveFormat: (wave: Wave, sampleRate: number, sampleSize: number, channels: number) -> (),
    LoadMusicStream: (fileName: string) -> Music,
    IsMusicValid: (music: Music) -> boolean,
    UnloadMusicStream: (music: Music) -> (),
    PlayMusicStream: (music: Music) -> (),
    IsMusicStreamPlaying: (music: Music) -> boolean,
    UpdateMusicStream: (music: Music) -> (),
    StopMusicStream: (music: Music) -> (),
    PauseMusicStream: (music: Music) -> (),
    ResumeMusicStream: (music: Music) -> (),
    SeekMusicStream: (music: Music, position: number) -> (),
    SetMusicVolume: (music: Music, volume: number) -> (),
    SetMusicPitch: (music: Music, pitch: number) -> (),
    SetMusicPan: (music: Music, pan: number) -> (),
    GetMusicTimeLength: (music: Music) -> number,
    GetMusicTimePlayed: (music: Music) -> number,
    LoadAudioStream: (sampleRate: number, sampleSize: number, channels: number) -> AudioStream,
    IsAudioStreamValid: (stream: AudioStream) -> boolean,
    UnloadAudioStream: (stream: AudioStream) -> (),
    IsAudioStreamProcessed: (stream: AudioStream) -> boolean,
    PlayAudioStream: (stream: AudioStream) -> (),
    PauseAudioStream: (stream: AudioStream) -> (),
    ResumeAudioStream: (stream: AudioStream) -> (),
    IsAudioStreamPlaying: (stream: AudioStream) -> boolean,
    StopAudioStream: (stream: AudioStream) -> (),
    SetAudioStreamVolume: (stream: AudioStream, volume: number) -> (),
    SetAudioStreamPitch: (stream: AudioStream, pitch: number) -> (),
    SetAudioStreamPan: (stream: AudioStream, pan: number) -> (),
    SetAudioStreamBufferSizeDefault: (size: number) -> (),

    Vector2: (x: number?, y: number?) -> vector,
    Vector3: (x: number?, y: number?, z: number?) -> vector,
    Color: (r: number?, g: number?, b: number?, a: number?) -> number,
    Vector4: (x: number?, y: number?, z: number?, w: number?) -> Vector4,
    Matrix: (m0: number?, m4: number?, m8: number?, m12: number?, m1: number?, m5: number?, m9: number?, m13: number?, m2: number?, m6: number?, m10: number?, m14: number?, m3: number?, m7: number?, m11: number?, m15: number?) -> Matrix,
    Rectangle: (x: number?, y: number?, width: number?, height: number?) -> Rectangle,
    Texture: (id: number?, width: number?, height: number?, mipmaps: number?, format: number?) -> Texture,
    RenderTexture: (id: number?, texture: Texture?, depth: Texture?) -> RenderTexture,
    NPatchInfo: (source: Rectangle?, left: number?, top: number?, right: number?, bottom: number?, layout: number?) -> NPatchInfo,
    Camera3D: (position: vector?, target: vector?, up: vector?, fovy: number?, projection: number?) -> Camera3D,
    Camera2D: (offset: vector?, target: vector?, rotation: number?, zoom: number?) -> Camera2D,
    MaterialMap: (texture: Texture?, color: number?, value: number?) -> MaterialMap,
    Transform: (translation: vector?, rotation: Vector4?, scale: vector?) -> Transform,
    BoneInfo: (parent: number?) -> BoneInfo,
    Ray: (position: vector?, direction: vector?) -> Ray,
    RayCollision: (hit: boolean?, distance: number?, point: vector?, normal: vector?) -> RayCollision,
    BoundingBox: (min: vector?, max: vector?) -> BoundingBox,
    VrDeviceInfo: (hResolution: number?, vResolution: number?, hScreenSize: number?, vScreenSize: number?, eyeToScreenDistance: number?, lensSeparationDistance: number?, interpupillaryDistance: number?) -> VrDeviceInfo,
    AutomationEvent: (frame: number?, type: number?) -> AutomationEvent,

    FLAG_VSYNC_HINT: number,
    FLAG_FULLSCREEN_MODE: number,
    FLAG_WINDOW_RESIZABLE: number,
    FLAG_WINDOW_UNDECORATED: number,
    FLAG_WINDOW_HIDDEN: number,
    FLAG_WINDOW_MINIMIZED: number,
    FLAG_WINDOW_MAXIMIZED: number,
    FLAG_WINDOW_UNFOCUSED: number,
    FLAG_WINDOW_TOPMOST: number,
    FLAG_WINDOW_ALWAYS_RUN: number,
    FLAG_WINDOW_TRANSPARENT: number,
    FLAG_WINDOW_HIGHDPI: number,
    FLAG_WINDOW_MOUSE_PASSTHROUGH: number,
    FLAG_BORDERLESS_WINDOWED_MODE: number,
    FLAG_MSAA_4X_HINT: number,
    FLAG_INTERLACED_HINT: number,
    LOG_ALL: number,
    LOG_TRACE: number,
    LOG_DEBUG: number,
    LOG_INFO: number,
    LOG_WARNING: number,
    LOG_ERROR: number,
    LOG_FATAL: number,
    LOG_NONE: number,
    KEY_NULL: number,
    KEY_APOSTROPHE: number,
    KEY_COMMA: number,
    KEY_MINUS: number,
    KEY_PERIOD: number,
    KEY_SLASH: number,
    KEY_ZERO: number,
    KEY_ONE: number,
    KEY_TWO: number,
    KEY_THREE: number,
    KEY_FOUR: number,
    KEY_FIVE: number,
    KEY_SIX: number,
    KEY_SEVEN: number,
    KEY_EIGHT: number,
    KEY_NINE: number,
    KEY_SEMICOLON: number,
    KEY_EQUAL: number,
    KEY_A: number,
    KEY_B: number,
    KEY_C: number,
    KEY_D: number,
    KEY_E: number,
    KEY_F: number,
    KEY_G: number,
    KEY_H: number,
    KEY_I: number,
    KEY_J: number,
    KEY_K: number,
    KEY_L: number,
    KEY_M: number,
    KEY_N: number,
    KEY_O: number,
    KEY_P: number,
    KEY_Q: number,
    KEY_R: number,
    KEY_S: number,
    KEY_T: number,
    KEY_U: number,
    KEY_V: number,
    KEY_W: number,
    KEY_X: number,
    KEY_Y: number,
    KEY_Z: number,
    KEY_LEFT_BRACKET: number,
    KEY_BACKSLASH: number,
    KEY_RIGHT_BRACKET: number,
    KEY_GRAVE: number,
    KEY_SPACE: number,
    KEY_ESCAPE: number,
    KEY_ENTER: number,
    KEY_TAB: number,
    KEY_BACKSPACE: number,
    KEY_INSERT: number,
    KEY_DELETE: number,
    KEY_RIGHT: number,
    KEY_LEFT: number,
    KEY_DOWN: number,
    KEY_UP: number,
    KEY_PAGE_UP: number,
    KEY_PAGE_DOWN: number,
    KEY_HOME: number,
    KEY_END: number,
    KEY_CAPS_LOCK: number,
    KEY_SCROLL_LOCK: number,
    KEY_NUM_LOCK: number,
    KEY_PRINT_SCREEN: number,
    KEY_PAUSE: number,
    KEY_F1: number,
    KEY_F2: number,
    KEY_F3: number,
    KEY_F4: number,
    KEY_F5: number,
    KEY_F6: number,
    KEY_F7: number,
    KEY_F8: number,
    KEY_F9: number,
    KEY_F10: number,
    KEY_F11: number,
    KEY_F12: number,
    KEY_LEFT_SHIFT: number,
    KEY_LEFT_CONTROL: number,
    KEY_LEFT_ALT: number,
    KEY_LEFT_SUPER: number,
    KEY_RIGHT_SHIFT: number,
    KEY_RIGHT_CONTROL: number,
    KEY_RIGHT_ALT: number,
    KEY_RIGHT_SUPER: number,
    KEY_KB_MENU: number,
    KEY_KP_0: number,
    KEY_KP_1: number,
    KEY_KP_2: number,
    KEY_KP_3: number,
    KEY_KP_4: number,
    KEY_KP_5: number,
    KEY_KP_6: number,
    KEY_KP_7: number,
    KEY_KP_8: number,
    KEY_KP_9: number,
    KEY_KP_DECIMAL: number,
    KEY_KP_DIVIDE: number,
    KEY_KP_MULTIPLY: number,
    KEY_KP_SUBTRACT: number,
    KEY_KP_ADD: number,
    KEY_KP_ENTER: number,
    KEY_KP_EQUAL: number,
    KEY_BACK: number,
    KEY_MENU: number,
    KEY_VOLUME_UP: number,
    KEY_VOLUME_DOWN: number,
    MOUSE_BUTTON_LEFT: number,
    MOUSE_BUTTON_RIGHT: number,
    MOUSE_BUTTON_MIDDLE: number,
    MOUSE_BUTTON_SIDE: number,
    MOUSE_BUTTON_EXTRA: number,
    MOUSE_BUTTON_FORWARD: number,
    MOUSE_BUTTON_BACK: number,
    MOUSE_CURSOR_DEFAULT: number,
    MOUSE_CURSOR_ARROW: number,
    MOUSE_CURSOR_IBEAM: number,
    MOUSE_CURSOR_CROSSHAIR: number,
    MOUSE_CURSOR_POINTING_HAND: number,
    MOUSE_CURSOR_RESIZE_EW: number,
    MOUSE_CURSOR_RESIZE_NS: number,
    MOUSE_CURSOR_RESIZE_NWSE: number,
    MOUSE_CURSOR_RESIZE_NESW: number,
    MOUSE_CURSOR_RESIZE_ALL: number,
    MOUSE_CURSOR_NOT_ALLOWED: number,
    GAMEPAD_BUTTON_UNKNOWN: number,
    GAMEPAD_BUTTON_LEFT_FACE_UP: number,
    GAMEPAD_BUTTON_LEFT_FACE_RIGHT: number,
    GAMEPAD_BUTTON_LEFT_FACE_DOWN: number,
    GAMEPAD_BUTTON_LEFT_FACE_LEFT: number,
    GAMEPAD_BUTTON_RIGHT_FACE_UP: number,
    GAMEPAD_BUTTON_RIGHT_FACE_RIGHT: number,
    GAMEPAD_BUTTON_RIGHT_FACE_DOWN: number,
    GAMEPAD_BUTTON_RIGHT_FACE_LEFT: number,
    GAMEPAD_BUTTON_LEFT_TRIGGER_1: number,
    GAMEPAD_BUTTON_LEFT_TRIGGER_2: number,
    GAMEPAD_BUTTON_RIGHT_TRIGGER_1: number,
    GAMEPAD_BUTTON_RIGHT_TRIGGER_2: number,
    GAMEPAD_BUTTON_MIDDLE_LEFT: number,
    GAMEPAD_BUTTON_MIDDLE: number,
    GAMEPAD_BUTTON_MIDDLE_RIGHT: number,
    GAMEPAD_BUTTON_LEFT_THUMB: number,
    GAMEPAD_BUTTON_RIGHT_THUMB: number,
    GAMEPAD_AXIS_LEFT_X: number,
    GAMEPAD_AXIS_LEFT_Y: number,
    GAMEPAD_AXIS_RIGHT_X: number,
    GAMEPAD_AXIS_RIGHT_Y: number,
    GAMEPAD_AXIS_LEFT_TRIGGER: number,
    GAMEPAD_AXIS_RIGHT_TRIGGER: number,
    MATERIAL_MAP_ALBEDO: number,
    MATERIAL_MAP_METALNESS: number,
    MATERIAL_MAP_NORMAL: number,
    MATERIAL_MAP_ROUGHNESS: number,
    MATERIAL_MAP_OCCLUSION: number,
    MATERIAL_MAP_EMISSION: number,
    MATERIAL_MAP_HEIGHT: number,
    MATERIAL_MAP_CUBEMAP: number,
    MATERIAL_MAP_IRRADIANCE: number,
    MATERIAL_MAP_PREFILTER: number,
    MATERIAL_MAP_BRDF: number,
    SHADER_LOC_VERTEX_POSITION: number,
    SHADER_LOC_VERTEX_TEXCOORD01: number,
    SHADER_LOC_VERTEX_TEXCOORD02: number,
    SHADER_LOC_VERTEX_NORMAL: number,
    SHADER_LOC_VERTEX_TANGENT: number,
    SHADER_LOC_VERTEX_COLOR: number,
    SHADER_LOC_MATRIX_MVP: number,
    SHADER_LOC_MATRIX_VIEW: number,
    SHADER_LOC_MATRIX_PROJECTION: number,
    SHADER_LOC_MATRIX_MODEL: number,
    SHADER_LOC_MATRIX_NORMAL: number,
    SHADER_LOC_VECTOR_VIEW: number,
    SHADER_LOC_COLOR_DIFFUSE: number,
    SHADER_LOC_COLOR_SPECULAR: number,
    SHADER_LOC_COLOR_AMBIENT: number,
    SHADER_LOC_MAP_ALBEDO: number,
    SHADER_LOC_MAP_METALNESS: number,
    SHADER_LOC_MAP_NORMAL: number,
    SHADER_LOC_MAP_ROUGHNESS: number,
    SHADER_LOC_MAP_OCCLUSION: number,
    SHADER_LOC_MAP_EMISSION: number,
    SHADER_LOC_MAP_HEIGHT: number,
    SHADER_LOC_MAP_CUBEMAP: number,
    SHADER_LOC_MAP_IRRADIANCE: number,
    SHADER_LOC_MAP_PREFILTER: number,
    SHADER_LOC_MAP_BRDF: number,
    SHADER_LOC_VERTEX_BONEIDS: number,
    SHADER_LOC_VERTEX_BONEWEIGHTS: number,
    SHADER_LOC_MATRIX_BONETRANSFORMS: number,
    SHADER_LOC_VERTEX_INSTANCETRANSFORM: number,
    SHADER_UNIFORM_FLOAT: number,
    SHADER_UNIFORM_VEC2: number,
    SHADER_UNIFORM_VEC3: number,
    SHADER_UNIFORM_VEC4: number,
    SHADER_UNIFORM_INT: number,
    SHADER_UNIFORM_IVEC2: number,
    SHADER_UNIFORM_IVEC3: number,
    SHADER_UNIFORM_IVEC4: number,
    SHADER_UNIFORM_UINT: number,
    SHADER_UNIFORM_UIVEC2: number,
    SHADER_UNIFORM_UIVEC3: number,
    SHADER_UNIFORM_UIVEC4: number,
    SHADER_UNIFORM_SAMPLER2D: number,
    SHADER_ATTRIB_FLOAT: number,
    SHADER_ATTRIB_VEC2: number,
    SHADER_ATTRIB_VEC3: number,
    SHADER_ATTRIB_VEC4: number,
    PIXELFORMAT_UNCOMPRESSED_GRAYSCALE: number,
    PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA: number,
    PIXELFORMAT_UNCOMPRESSED_R5G6B5: number,
    PIXELFORMAT_UNCOMPRESSED_R8G8B8: number,
    PIXELFORMAT_UNCOMPRESSED_R5G5B5A1: number,
    PIXELFORMAT_UNCOMPRESSED_R4G4B4A4: number,
    PIXELFORMAT_UNCOMPRESSED_R8G8B8A8: number,
    PIXELFORMAT_UNCOMPRESSED_R32: number,
    PIXELFORMAT_UNCOMPRESSED_R32G32B32: number,
    PIXELFORMAT_UNCOMPRESSED_R32G32B32A32: number,
    PIXELFORMAT_UNCOMPRESSED_R16: number,
    PIXELFORMAT_UNCOMPRESSED_R16G16B16: number,
    PIXELFORMAT_UNCOMPRESSED_R16G16B16A16: number,
    PIXELFORMAT_COMPRESSED_DXT1_RGB: number,
    PIXELFORMAT_COMPRESSED_DXT1_RGBA: number,
    PIXELFORMAT_COMPRESSED_DXT3_RGBA: number,
    PIXELFORMAT_COMPRESSED_DXT5_RGBA: number,
    PIXELFORMAT_COMPRESSED_ETC1_RGB: number,
    PIXELFORMAT_COMPRESSED_ETC2_RGB: number,
    PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA: number,
    PIXELFORMAT_COMPRESSED_PVRT_RGB: number,
    PIXELFORMAT_COMPRESSED_PVRT_RGBA: number,
    PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA: number,
    PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA: number,
    TEXTURE_FILTER_POINT: number,
    TEXTURE_FILTER_BILINEAR: number,
    TEXTURE_FILTER_TRILINEAR: number,
    TEXTURE_FILTER_ANISOTROPIC_4X: number,
    TEXTURE_FILTER_ANISOTROPIC_8X: number,
    TEXTURE_FILTER_ANISOTROPIC_16X: number,
    TEXTURE_WRAP_REPEAT: number,
    TEXTURE_WRAP_CLAMP: number,
    TEXTURE_WRAP_MIRROR_REPEAT: number,
    TEXTURE_WRAP_MIRROR_CLAMP: number,
    CUBEMAP_LAYOUT_AUTO_DETECT: number,
    CUBEMAP_LAYOUT_LINE_VERTICAL: number,
    CUBEMAP_LAYOUT_LINE_HORIZONTAL: number,
    CUBEMAP_LAYOUT_CROSS_THREE_BY_FOUR: number,
    CUBEMAP_LAYOUT_CROSS_FOUR_BY_THREE: number,
    FONT_DEFAULT: number,
    FONT_BITMAP: number,
    FONT_SDF: number,
    BLEND_ALPHA: number,
    BLEND_ADDITIVE: number,
    BLEND_MULTIPLIED: number,
    BLEND_ADD_COLORS: number,
    BLEND_SUBTRACT_COLORS: number,
    BLEND_ALPHA_PREMULTIPLY: number,
    BLEND_CUSTOM: number,
    BLEND_CUSTOM_SEPARATE: number,
    GESTURE_NONE: number,
    GESTURE_TAP: number,
    GESTURE_DOUBLETAP: number,
    GESTURE_HOLD: number,
    GESTURE_DRAG: number,
    GESTURE_SWIPE_RIGHT: number,
    GESTURE_SWIPE_LEFT: number,
    GESTURE_SWIPE_UP: number,
    GESTURE_SWIPE_DOWN: number,
    GESTURE_PINCH_IN: number,
    GESTURE_PINCH_OUT: number,
    CAMERA_CUSTOM: number,
    CAMERA_FREE: number,
    CAMERA_ORBITAL: number,
    CAMERA_FIRST_PERSON: number,
    CAMERA_THIRD_PERSON: number,
    CAMERA_PERSPECTIVE: number,
    CAMERA_ORTHOGRAPHIC: number,
    NPATCH_NINE_PATCH: number,
    NPATCH_THREE_PATCH_VERTICAL: number,
    NPATCH_THREE_PATCH_HORIZONTAL: number,
    RAYLIB_VERSION_MAJOR: number,
    RAYLIB_VERSION_MINOR: number,
    RAYLIB_VERSION_PATCH: number,
    PI: number,
    DEG2RAD: number,
    RAD2DEG: number,
    LIGHTGRAY: number,
    GRAY: number,
    DARKGRAY: number,
    YELLOW: number,
    GOLD: number,
    ORANGE: number,
    PINK: number,
    RED: number,
    MAROON: number,
    GREEN: number,
    LIME: number,
    DARKGREEN: number,
    SKYBLUE: number,
    BLUE: number,
    DARKBLUE: number,
    PURPLE: number,
    VIOLET: number,
    DARKPURPLE: number,
    BEIGE: number,
    BROWN: number,
    DARKBROWN: number,
    WHITE: number,
    BLACK: number,
    BLANK: number,
    MAGENTA: number,
    RAYWHITE: number,
}
