// generated by tools/bindgen.py from raylib 6.0, do not edit
// run ./build.sh bindgen after a raylib bump
#pragma once

#include "bind.hpp"
#include "raylib.h"

namespace bind {

template <> struct UdTraits<Vector4> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 1;
    static constexpr const char *kName = "Vector4";
};
template <> struct UdTraits<Matrix> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 2;
    static constexpr const char *kName = "Matrix";
};
template <> struct UdTraits<Rectangle> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 3;
    static constexpr const char *kName = "Rectangle";
};
template <> struct UdTraits<Image> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 4;
    static constexpr const char *kName = "Image";
};
template <> struct UdTraits<Texture> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 5;
    static constexpr const char *kName = "Texture";
};
template <> struct UdTraits<RenderTexture> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 6;
    static constexpr const char *kName = "RenderTexture";
};
template <> struct UdTraits<NPatchInfo> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 7;
    static constexpr const char *kName = "NPatchInfo";
};
template <> struct UdTraits<GlyphInfo> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 8;
    static constexpr const char *kName = "GlyphInfo";
};
template <> struct UdTraits<Font> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 9;
    static constexpr const char *kName = "Font";
};
template <> struct UdTraits<Camera3D> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 10;
    static constexpr const char *kName = "Camera3D";
};
template <> struct UdTraits<Camera2D> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 11;
    static constexpr const char *kName = "Camera2D";
};
template <> struct UdTraits<Mesh> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 12;
    static constexpr const char *kName = "Mesh";
};
template <> struct UdTraits<Shader> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 13;
    static constexpr const char *kName = "Shader";
};
template <> struct UdTraits<MaterialMap> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 14;
    static constexpr const char *kName = "MaterialMap";
};
template <> struct UdTraits<Material> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 15;
    static constexpr const char *kName = "Material";
};
template <> struct UdTraits<Transform> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 16;
    static constexpr const char *kName = "Transform";
};
template <> struct UdTraits<BoneInfo> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 17;
    static constexpr const char *kName = "BoneInfo";
};
template <> struct UdTraits<ModelSkeleton> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 18;
    static constexpr const char *kName = "ModelSkeleton";
};
template <> struct UdTraits<Model> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 19;
    static constexpr const char *kName = "Model";
};
template <> struct UdTraits<ModelAnimation> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 20;
    static constexpr const char *kName = "ModelAnimation";
};
template <> struct UdTraits<Ray> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 21;
    static constexpr const char *kName = "Ray";
};
template <> struct UdTraits<RayCollision> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 22;
    static constexpr const char *kName = "RayCollision";
};
template <> struct UdTraits<BoundingBox> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 23;
    static constexpr const char *kName = "BoundingBox";
};
template <> struct UdTraits<Wave> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 24;
    static constexpr const char *kName = "Wave";
};
template <> struct UdTraits<AudioStream> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 25;
    static constexpr const char *kName = "AudioStream";
};
template <> struct UdTraits<Sound> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 26;
    static constexpr const char *kName = "Sound";
};
template <> struct UdTraits<Music> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 27;
    static constexpr const char *kName = "Music";
};
template <> struct UdTraits<VrDeviceInfo> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 28;
    static constexpr const char *kName = "VrDeviceInfo";
};
template <> struct UdTraits<VrStereoConfig> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 29;
    static constexpr const char *kName = "VrStereoConfig";
};
template <> struct UdTraits<FilePathList> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 30;
    static constexpr const char *kName = "FilePathList";
};
template <> struct UdTraits<AutomationEvent> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 31;
    static constexpr const char *kName = "AutomationEvent";
};
template <> struct UdTraits<AutomationEventList> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 32;
    static constexpr const char *kName = "AutomationEventList";
};

inline constexpr int kRaylibTagCount = 32;
static_assert(kRaylibTagCount < kReleasedTag, "raylib tags collide with the released tag");

}  // namespace bind

// Creates the raylib global and userdata metatables for this VM.
void OpenRaylib(lua_State *L);
