// Generated by tools/bindgen.py from raylib 6.0. Do not edit.
//
// Rerun ./build.sh bindgen after bumping raylib in build.zig.zon. The report of
// everything that is deliberately not bound is at the bottom of this file.

#include "raylib_bind.hpp"

#include "bind.hpp"
#include "rl_adapters.hpp"
#include "rl_types.hpp"

namespace bind {

// userdata tags, 1 based because tag 0 belongs to plain lua_newuserdata
template <> struct UdTraits<Vector4> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 1;
    static constexpr const char *kName = "Vector4";
};
template <> struct UdTraits<Matrix> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 2;
    static constexpr const char *kName = "Matrix";
};
template <> struct UdTraits<Rectangle> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 3;
    static constexpr const char *kName = "Rectangle";
};
template <> struct UdTraits<Image> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 4;
    static constexpr const char *kName = "Image";
};
template <> struct UdTraits<Texture> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 5;
    static constexpr const char *kName = "Texture";
};
template <> struct UdTraits<RenderTexture> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 6;
    static constexpr const char *kName = "RenderTexture";
};
template <> struct UdTraits<NPatchInfo> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 7;
    static constexpr const char *kName = "NPatchInfo";
};
template <> struct UdTraits<GlyphInfo> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 8;
    static constexpr const char *kName = "GlyphInfo";
};
template <> struct UdTraits<Font> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 9;
    static constexpr const char *kName = "Font";
};
template <> struct UdTraits<Camera3D> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 10;
    static constexpr const char *kName = "Camera3D";
};
template <> struct UdTraits<Camera2D> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 11;
    static constexpr const char *kName = "Camera2D";
};
template <> struct UdTraits<Mesh> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 12;
    static constexpr const char *kName = "Mesh";
};
template <> struct UdTraits<Shader> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 13;
    static constexpr const char *kName = "Shader";
};
template <> struct UdTraits<MaterialMap> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 14;
    static constexpr const char *kName = "MaterialMap";
};
template <> struct UdTraits<Material> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 15;
    static constexpr const char *kName = "Material";
};
template <> struct UdTraits<Transform> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 16;
    static constexpr const char *kName = "Transform";
};
template <> struct UdTraits<BoneInfo> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 17;
    static constexpr const char *kName = "BoneInfo";
};
template <> struct UdTraits<ModelSkeleton> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 18;
    static constexpr const char *kName = "ModelSkeleton";
};
template <> struct UdTraits<Model> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 19;
    static constexpr const char *kName = "Model";
};
template <> struct UdTraits<ModelAnimation> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 20;
    static constexpr const char *kName = "ModelAnimation";
};
template <> struct UdTraits<Ray> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 21;
    static constexpr const char *kName = "Ray";
};
template <> struct UdTraits<RayCollision> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 22;
    static constexpr const char *kName = "RayCollision";
};
template <> struct UdTraits<BoundingBox> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 23;
    static constexpr const char *kName = "BoundingBox";
};
template <> struct UdTraits<Wave> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 24;
    static constexpr const char *kName = "Wave";
};
template <> struct UdTraits<AudioStream> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 25;
    static constexpr const char *kName = "AudioStream";
};
template <> struct UdTraits<Sound> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 26;
    static constexpr const char *kName = "Sound";
};
template <> struct UdTraits<Music> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 27;
    static constexpr const char *kName = "Music";
};
template <> struct UdTraits<VrDeviceInfo> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 28;
    static constexpr const char *kName = "VrDeviceInfo";
};
template <> struct UdTraits<VrStereoConfig> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 29;
    static constexpr const char *kName = "VrStereoConfig";
};
template <> struct UdTraits<FilePathList> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 30;
    static constexpr const char *kName = "FilePathList";
};
template <> struct UdTraits<AutomationEvent> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 31;
    static constexpr const char *kName = "AutomationEvent";
};
template <> struct UdTraits<AutomationEventList> {
    static constexpr bool kBound = true;
    static constexpr int kTag = 32;
    static constexpr const char *kName = "AutomationEventList";
};

}  // namespace bind

namespace {

using bind::Field;
using bind::FieldDef;
using bind::TypeInfo;

const FieldDef kFieldsVector4[] = {
    {"w", &Field<&Vector4::w>::Get, &Field<&Vector4::w>::Set},
    {"x", &Field<&Vector4::x>::Get, &Field<&Vector4::x>::Set},
    {"y", &Field<&Vector4::y>::Get, &Field<&Vector4::y>::Set},
    {"z", &Field<&Vector4::z>::Get, &Field<&Vector4::z>::Set},
};
const TypeInfo kTypeVector4 = {"Vector4", 1, kFieldsVector4, 4};

const FieldDef kFieldsMatrix[] = {
    {"m0", &Field<&Matrix::m0>::Get, &Field<&Matrix::m0>::Set},
    {"m1", &Field<&Matrix::m1>::Get, &Field<&Matrix::m1>::Set},
    {"m10", &Field<&Matrix::m10>::Get, &Field<&Matrix::m10>::Set},
    {"m11", &Field<&Matrix::m11>::Get, &Field<&Matrix::m11>::Set},
    {"m12", &Field<&Matrix::m12>::Get, &Field<&Matrix::m12>::Set},
    {"m13", &Field<&Matrix::m13>::Get, &Field<&Matrix::m13>::Set},
    {"m14", &Field<&Matrix::m14>::Get, &Field<&Matrix::m14>::Set},
    {"m15", &Field<&Matrix::m15>::Get, &Field<&Matrix::m15>::Set},
    {"m2", &Field<&Matrix::m2>::Get, &Field<&Matrix::m2>::Set},
    {"m3", &Field<&Matrix::m3>::Get, &Field<&Matrix::m3>::Set},
    {"m4", &Field<&Matrix::m4>::Get, &Field<&Matrix::m4>::Set},
    {"m5", &Field<&Matrix::m5>::Get, &Field<&Matrix::m5>::Set},
    {"m6", &Field<&Matrix::m6>::Get, &Field<&Matrix::m6>::Set},
    {"m7", &Field<&Matrix::m7>::Get, &Field<&Matrix::m7>::Set},
    {"m8", &Field<&Matrix::m8>::Get, &Field<&Matrix::m8>::Set},
    {"m9", &Field<&Matrix::m9>::Get, &Field<&Matrix::m9>::Set},
};
const TypeInfo kTypeMatrix = {"Matrix", 2, kFieldsMatrix, 16};

const FieldDef kFieldsRectangle[] = {
    {"height", &Field<&Rectangle::height>::Get, &Field<&Rectangle::height>::Set},
    {"width", &Field<&Rectangle::width>::Get, &Field<&Rectangle::width>::Set},
    {"x", &Field<&Rectangle::x>::Get, &Field<&Rectangle::x>::Set},
    {"y", &Field<&Rectangle::y>::Get, &Field<&Rectangle::y>::Set},
};
const TypeInfo kTypeRectangle = {"Rectangle", 3, kFieldsRectangle, 4};

const FieldDef kFieldsImage[] = {
    {"format", &Field<&Image::format>::Get, nullptr},
    {"height", &Field<&Image::height>::Get, nullptr},
    {"mipmaps", &Field<&Image::mipmaps>::Get, nullptr},
    {"width", &Field<&Image::width>::Get, nullptr},
};
const TypeInfo kTypeImage = {"Image", 4, kFieldsImage, 4};

const FieldDef kFieldsTexture[] = {
    {"format", &Field<&Texture::format>::Get, &Field<&Texture::format>::Set},
    {"height", &Field<&Texture::height>::Get, &Field<&Texture::height>::Set},
    {"id", &Field<&Texture::id>::Get, &Field<&Texture::id>::Set},
    {"mipmaps", &Field<&Texture::mipmaps>::Get, &Field<&Texture::mipmaps>::Set},
    {"width", &Field<&Texture::width>::Get, &Field<&Texture::width>::Set},
};
const TypeInfo kTypeTexture = {"Texture", 5, kFieldsTexture, 5};

const FieldDef kFieldsRenderTexture[] = {
    {"depth", &Field<&RenderTexture::depth>::Get, &Field<&RenderTexture::depth>::Set},
    {"id", &Field<&RenderTexture::id>::Get, &Field<&RenderTexture::id>::Set},
    {"texture", &Field<&RenderTexture::texture>::Get, &Field<&RenderTexture::texture>::Set},
};
const TypeInfo kTypeRenderTexture = {"RenderTexture", 6, kFieldsRenderTexture, 3};

const FieldDef kFieldsNPatchInfo[] = {
    {"bottom", &Field<&NPatchInfo::bottom>::Get, &Field<&NPatchInfo::bottom>::Set},
    {"layout", &Field<&NPatchInfo::layout>::Get, &Field<&NPatchInfo::layout>::Set},
    {"left", &Field<&NPatchInfo::left>::Get, &Field<&NPatchInfo::left>::Set},
    {"right", &Field<&NPatchInfo::right>::Get, &Field<&NPatchInfo::right>::Set},
    {"source", &Field<&NPatchInfo::source>::Get, &Field<&NPatchInfo::source>::Set},
    {"top", &Field<&NPatchInfo::top>::Get, &Field<&NPatchInfo::top>::Set},
};
const TypeInfo kTypeNPatchInfo = {"NPatchInfo", 7, kFieldsNPatchInfo, 6};

const FieldDef kFieldsGlyphInfo[] = {
    {"advanceX", &Field<&GlyphInfo::advanceX>::Get, nullptr},
    {"offsetX", &Field<&GlyphInfo::offsetX>::Get, nullptr},
    {"offsetY", &Field<&GlyphInfo::offsetY>::Get, nullptr},
    {"value", &Field<&GlyphInfo::value>::Get, nullptr},
};
const TypeInfo kTypeGlyphInfo = {"GlyphInfo", 8, kFieldsGlyphInfo, 4};

const FieldDef kFieldsFont[] = {
    {"baseSize", &Field<&Font::baseSize>::Get, nullptr},
    {"glyphCount", &Field<&Font::glyphCount>::Get, nullptr},
    {"glyphPadding", &Field<&Font::glyphPadding>::Get, nullptr},
    {"texture", &Field<&Font::texture>::Get, &Field<&Font::texture>::Set},
};
const TypeInfo kTypeFont = {"Font", 9, kFieldsFont, 4};

const FieldDef kFieldsCamera3D[] = {
    {"fovy", &Field<&Camera3D::fovy>::Get, &Field<&Camera3D::fovy>::Set},
    {"position", &Field<&Camera3D::position>::Get, &Field<&Camera3D::position>::Set},
    {"projection", &Field<&Camera3D::projection>::Get, &Field<&Camera3D::projection>::Set},
    {"target", &Field<&Camera3D::target>::Get, &Field<&Camera3D::target>::Set},
    {"up", &Field<&Camera3D::up>::Get, &Field<&Camera3D::up>::Set},
};
const TypeInfo kTypeCamera3D = {"Camera3D", 10, kFieldsCamera3D, 5};

const FieldDef kFieldsCamera2D[] = {
    {"offset", &Field<&Camera2D::offset>::Get, &Field<&Camera2D::offset>::Set},
    {"rotation", &Field<&Camera2D::rotation>::Get, &Field<&Camera2D::rotation>::Set},
    {"target", &Field<&Camera2D::target>::Get, &Field<&Camera2D::target>::Set},
    {"zoom", &Field<&Camera2D::zoom>::Get, &Field<&Camera2D::zoom>::Set},
};
const TypeInfo kTypeCamera2D = {"Camera2D", 11, kFieldsCamera2D, 4};

const FieldDef kFieldsMesh[] = {
    {"boneCount", &Field<&Mesh::boneCount>::Get, nullptr},
    {"triangleCount", &Field<&Mesh::triangleCount>::Get, nullptr},
    {"vaoId", &Field<&Mesh::vaoId>::Get, nullptr},
    {"vertexCount", &Field<&Mesh::vertexCount>::Get, nullptr},
};
const TypeInfo kTypeMesh = {"Mesh", 12, kFieldsMesh, 4};

const FieldDef kFieldsShader[] = {
    {"id", &Field<&Shader::id>::Get, nullptr},
};
const TypeInfo kTypeShader = {"Shader", 13, kFieldsShader, 1};

const FieldDef kFieldsMaterialMap[] = {
    {"color", &Field<&MaterialMap::color>::Get, &Field<&MaterialMap::color>::Set},
    {"texture", &Field<&MaterialMap::texture>::Get, &Field<&MaterialMap::texture>::Set},
    {"value", &Field<&MaterialMap::value>::Get, &Field<&MaterialMap::value>::Set},
};
const TypeInfo kTypeMaterialMap = {"MaterialMap", 14, kFieldsMaterialMap, 3};

const TypeInfo kTypeMaterial = {"Material", 15, nullptr, 0};

const FieldDef kFieldsTransform[] = {
    {"rotation", &Field<&Transform::rotation>::Get, &Field<&Transform::rotation>::Set},
    {"scale", &Field<&Transform::scale>::Get, &Field<&Transform::scale>::Set},
    {"translation", &Field<&Transform::translation>::Get, &Field<&Transform::translation>::Set},
};
const TypeInfo kTypeTransform = {"Transform", 16, kFieldsTransform, 3};

const FieldDef kFieldsBoneInfo[] = {
    {"parent", &Field<&BoneInfo::parent>::Get, &Field<&BoneInfo::parent>::Set},
};
const TypeInfo kTypeBoneInfo = {"BoneInfo", 17, kFieldsBoneInfo, 1};

const FieldDef kFieldsModelSkeleton[] = {
    {"boneCount", &Field<&ModelSkeleton::boneCount>::Get, nullptr},
};
const TypeInfo kTypeModelSkeleton = {"ModelSkeleton", 18, kFieldsModelSkeleton, 1};

const FieldDef kFieldsModel[] = {
    {"materialCount", &Field<&Model::materialCount>::Get, nullptr},
    {"meshCount", &Field<&Model::meshCount>::Get, nullptr},
    {"transform", &Field<&Model::transform>::Get, &Field<&Model::transform>::Set},
};
const TypeInfo kTypeModel = {"Model", 19, kFieldsModel, 3};

const FieldDef kFieldsModelAnimation[] = {
    {"boneCount", &Field<&ModelAnimation::boneCount>::Get, nullptr},
    {"keyframeCount", &Field<&ModelAnimation::keyframeCount>::Get, nullptr},
};
const TypeInfo kTypeModelAnimation = {"ModelAnimation", 20, kFieldsModelAnimation, 2};

const FieldDef kFieldsRay[] = {
    {"direction", &Field<&Ray::direction>::Get, &Field<&Ray::direction>::Set},
    {"position", &Field<&Ray::position>::Get, &Field<&Ray::position>::Set},
};
const TypeInfo kTypeRay = {"Ray", 21, kFieldsRay, 2};

const FieldDef kFieldsRayCollision[] = {
    {"distance", &Field<&RayCollision::distance>::Get, &Field<&RayCollision::distance>::Set},
    {"hit", &Field<&RayCollision::hit>::Get, &Field<&RayCollision::hit>::Set},
    {"normal", &Field<&RayCollision::normal>::Get, &Field<&RayCollision::normal>::Set},
    {"point", &Field<&RayCollision::point>::Get, &Field<&RayCollision::point>::Set},
};
const TypeInfo kTypeRayCollision = {"RayCollision", 22, kFieldsRayCollision, 4};

const FieldDef kFieldsBoundingBox[] = {
    {"max", &Field<&BoundingBox::max>::Get, &Field<&BoundingBox::max>::Set},
    {"min", &Field<&BoundingBox::min>::Get, &Field<&BoundingBox::min>::Set},
};
const TypeInfo kTypeBoundingBox = {"BoundingBox", 23, kFieldsBoundingBox, 2};

const FieldDef kFieldsWave[] = {
    {"channels", &Field<&Wave::channels>::Get, nullptr},
    {"frameCount", &Field<&Wave::frameCount>::Get, nullptr},
    {"sampleRate", &Field<&Wave::sampleRate>::Get, nullptr},
    {"sampleSize", &Field<&Wave::sampleSize>::Get, nullptr},
};
const TypeInfo kTypeWave = {"Wave", 24, kFieldsWave, 4};

const FieldDef kFieldsAudioStream[] = {
    {"channels", &Field<&AudioStream::channels>::Get, nullptr},
    {"sampleRate", &Field<&AudioStream::sampleRate>::Get, nullptr},
    {"sampleSize", &Field<&AudioStream::sampleSize>::Get, nullptr},
};
const TypeInfo kTypeAudioStream = {"AudioStream", 25, kFieldsAudioStream, 3};

const FieldDef kFieldsSound[] = {
    {"frameCount", &Field<&Sound::frameCount>::Get, nullptr},
};
const TypeInfo kTypeSound = {"Sound", 26, kFieldsSound, 1};

const FieldDef kFieldsMusic[] = {
    {"ctxType", &Field<&Music::ctxType>::Get, nullptr},
    {"frameCount", &Field<&Music::frameCount>::Get, nullptr},
    {"looping", &Field<&Music::looping>::Get, &Field<&Music::looping>::Set},
};
const TypeInfo kTypeMusic = {"Music", 27, kFieldsMusic, 3};

const FieldDef kFieldsVrDeviceInfo[] = {
    {"eyeToScreenDistance", &Field<&VrDeviceInfo::eyeToScreenDistance>::Get, &Field<&VrDeviceInfo::eyeToScreenDistance>::Set},
    {"hResolution", &Field<&VrDeviceInfo::hResolution>::Get, &Field<&VrDeviceInfo::hResolution>::Set},
    {"hScreenSize", &Field<&VrDeviceInfo::hScreenSize>::Get, &Field<&VrDeviceInfo::hScreenSize>::Set},
    {"interpupillaryDistance", &Field<&VrDeviceInfo::interpupillaryDistance>::Get, &Field<&VrDeviceInfo::interpupillaryDistance>::Set},
    {"lensSeparationDistance", &Field<&VrDeviceInfo::lensSeparationDistance>::Get, &Field<&VrDeviceInfo::lensSeparationDistance>::Set},
    {"vResolution", &Field<&VrDeviceInfo::vResolution>::Get, &Field<&VrDeviceInfo::vResolution>::Set},
    {"vScreenSize", &Field<&VrDeviceInfo::vScreenSize>::Get, &Field<&VrDeviceInfo::vScreenSize>::Set},
};
const TypeInfo kTypeVrDeviceInfo = {"VrDeviceInfo", 28, kFieldsVrDeviceInfo, 7};

const TypeInfo kTypeVrStereoConfig = {"VrStereoConfig", 29, nullptr, 0};

const FieldDef kFieldsFilePathList[] = {
    {"count", &Field<&FilePathList::count>::Get, nullptr},
};
const TypeInfo kTypeFilePathList = {"FilePathList", 30, kFieldsFilePathList, 1};

const FieldDef kFieldsAutomationEvent[] = {
    {"frame", &Field<&AutomationEvent::frame>::Get, &Field<&AutomationEvent::frame>::Set},
    {"type", &Field<&AutomationEvent::type>::Get, &Field<&AutomationEvent::type>::Set},
};
const TypeInfo kTypeAutomationEvent = {"AutomationEvent", 31, kFieldsAutomationEvent, 2};

const FieldDef kFieldsAutomationEventList[] = {
    {"capacity", &Field<&AutomationEventList::capacity>::Get, nullptr},
    {"count", &Field<&AutomationEventList::count>::Get, nullptr},
};
const TypeInfo kTypeAutomationEventList = {"AutomationEventList", 32, kFieldsAutomationEventList, 2};

const TypeInfo *const kTypes[] = {
    &kTypeVector4,
    &kTypeMatrix,
    &kTypeRectangle,
    &kTypeImage,
    &kTypeTexture,
    &kTypeRenderTexture,
    &kTypeNPatchInfo,
    &kTypeGlyphInfo,
    &kTypeFont,
    &kTypeCamera3D,
    &kTypeCamera2D,
    &kTypeMesh,
    &kTypeShader,
    &kTypeMaterialMap,
    &kTypeMaterial,
    &kTypeTransform,
    &kTypeBoneInfo,
    &kTypeModelSkeleton,
    &kTypeModel,
    &kTypeModelAnimation,
    &kTypeRay,
    &kTypeRayCollision,
    &kTypeBoundingBox,
    &kTypeWave,
    &kTypeAudioStream,
    &kTypeSound,
    &kTypeMusic,
    &kTypeVrDeviceInfo,
    &kTypeVrStereoConfig,
    &kTypeFilePathList,
    &kTypeAutomationEvent,
    &kTypeAutomationEventList,
};

struct FnDef {
    const char *name;
    lua_CFunction fn;
};

const FnDef kFunctions[] = {
    {"InitWindow", BIND_FN(InitWindow)},
    {"CloseWindow", BIND_FN(CloseWindow)},
    {"WindowShouldClose", BIND_FN(WindowShouldClose)},
    {"IsWindowReady", BIND_FN(IsWindowReady)},
    {"IsWindowFullscreen", BIND_FN(IsWindowFullscreen)},
    {"IsWindowHidden", BIND_FN(IsWindowHidden)},
    {"IsWindowMinimized", BIND_FN(IsWindowMinimized)},
    {"IsWindowMaximized", BIND_FN(IsWindowMaximized)},
    {"IsWindowFocused", BIND_FN(IsWindowFocused)},
    {"IsWindowResized", BIND_FN(IsWindowResized)},
    {"IsWindowState", BIND_FN(IsWindowState)},
    {"SetWindowState", BIND_FN(SetWindowState)},
    {"ClearWindowState", BIND_FN(ClearWindowState)},
    {"ToggleFullscreen", BIND_FN(ToggleFullscreen)},
    {"ToggleBorderlessWindowed", BIND_FN(ToggleBorderlessWindowed)},
    {"MaximizeWindow", BIND_FN(MaximizeWindow)},
    {"MinimizeWindow", BIND_FN(MinimizeWindow)},
    {"RestoreWindow", BIND_FN(RestoreWindow)},
    {"SetWindowIcon", BIND_FN(SetWindowIcon)},
    {"SetWindowTitle", BIND_FN(SetWindowTitle)},
    {"SetWindowPosition", BIND_FN(SetWindowPosition)},
    {"SetWindowMonitor", BIND_FN(SetWindowMonitor)},
    {"SetWindowMinSize", BIND_FN(SetWindowMinSize)},
    {"SetWindowMaxSize", BIND_FN(SetWindowMaxSize)},
    {"SetWindowSize", BIND_FN(SetWindowSize)},
    {"SetWindowOpacity", BIND_FN(SetWindowOpacity)},
    {"SetWindowFocused", BIND_FN(SetWindowFocused)},
    {"GetScreenWidth", BIND_FN(GetScreenWidth)},
    {"GetScreenHeight", BIND_FN(GetScreenHeight)},
    {"GetRenderWidth", BIND_FN(GetRenderWidth)},
    {"GetRenderHeight", BIND_FN(GetRenderHeight)},
    {"GetMonitorCount", BIND_FN(GetMonitorCount)},
    {"GetCurrentMonitor", BIND_FN(GetCurrentMonitor)},
    {"GetMonitorPosition", BIND_FN(GetMonitorPosition)},
    {"GetMonitorWidth", BIND_FN(GetMonitorWidth)},
    {"GetMonitorHeight", BIND_FN(GetMonitorHeight)},
    {"GetMonitorPhysicalWidth", BIND_FN(GetMonitorPhysicalWidth)},
    {"GetMonitorPhysicalHeight", BIND_FN(GetMonitorPhysicalHeight)},
    {"GetMonitorRefreshRate", BIND_FN(GetMonitorRefreshRate)},
    {"GetWindowPosition", BIND_FN(GetWindowPosition)},
    {"GetWindowScaleDPI", BIND_FN(GetWindowScaleDPI)},
    {"GetMonitorName", BIND_FN(GetMonitorName)},
    {"SetClipboardText", BIND_FN(SetClipboardText)},
    {"GetClipboardText", BIND_FN(GetClipboardText)},
    {"GetClipboardImage", BIND_FN(GetClipboardImage)},
    {"EnableEventWaiting", BIND_FN(EnableEventWaiting)},
    {"DisableEventWaiting", BIND_FN(DisableEventWaiting)},
    {"ShowCursor", BIND_FN(ShowCursor)},
    {"HideCursor", BIND_FN(HideCursor)},
    {"IsCursorHidden", BIND_FN(IsCursorHidden)},
    {"EnableCursor", BIND_FN(EnableCursor)},
    {"DisableCursor", BIND_FN(DisableCursor)},
    {"IsCursorOnScreen", BIND_FN(IsCursorOnScreen)},
    {"ClearBackground", BIND_FN(ClearBackground)},
    {"BeginDrawing", BIND_FN(BeginDrawing)},
    {"EndDrawing", BIND_FN(EndDrawing)},
    {"BeginMode2D", BIND_FN(BeginMode2D)},
    {"EndMode2D", BIND_FN(EndMode2D)},
    {"BeginMode3D", BIND_FN(BeginMode3D)},
    {"EndMode3D", BIND_FN(EndMode3D)},
    {"BeginTextureMode", BIND_FN(BeginTextureMode)},
    {"EndTextureMode", BIND_FN(EndTextureMode)},
    {"BeginShaderMode", BIND_FN(BeginShaderMode)},
    {"EndShaderMode", BIND_FN(EndShaderMode)},
    {"BeginBlendMode", BIND_FN(BeginBlendMode)},
    {"EndBlendMode", BIND_FN(EndBlendMode)},
    {"BeginScissorMode", BIND_FN(BeginScissorMode)},
    {"EndScissorMode", BIND_FN(EndScissorMode)},
    {"BeginVrStereoMode", BIND_FN(BeginVrStereoMode)},
    {"EndVrStereoMode", BIND_FN(EndVrStereoMode)},
    {"LoadVrStereoConfig", BIND_FN(LoadVrStereoConfig)},
    {"UnloadVrStereoConfig", BIND_UNLOAD(UnloadVrStereoConfig)},
    {"LoadShader", BIND_FN(LoadShader)},
    {"LoadShaderFromMemory", BIND_FN(LoadShaderFromMemory)},
    {"IsShaderValid", BIND_FN(IsShaderValid)},
    {"GetShaderLocation", BIND_FN(GetShaderLocation)},
    {"GetShaderLocationAttrib", BIND_FN(GetShaderLocationAttrib)},
    {"SetShaderValueMatrix", BIND_FN(SetShaderValueMatrix)},
    {"SetShaderValueTexture", BIND_FN(SetShaderValueTexture)},
    {"UnloadShader", BIND_UNLOAD(UnloadShader)},
    {"GetScreenToWorldRay", BIND_FN(GetScreenToWorldRay)},
    {"GetScreenToWorldRayEx", BIND_FN(GetScreenToWorldRayEx)},
    {"GetWorldToScreen", BIND_FN(GetWorldToScreen)},
    {"GetWorldToScreenEx", BIND_FN(GetWorldToScreenEx)},
    {"GetWorldToScreen2D", BIND_FN(GetWorldToScreen2D)},
    {"GetScreenToWorld2D", BIND_FN(GetScreenToWorld2D)},
    {"GetCameraMatrix", BIND_FN(GetCameraMatrix)},
    {"GetCameraMatrix2D", BIND_FN(GetCameraMatrix2D)},
    {"SetTargetFPS", BIND_FN(SetTargetFPS)},
    {"GetFrameTime", BIND_FN(GetFrameTime)},
    {"GetTime", BIND_FN(GetTime)},
    {"GetFPS", BIND_FN(GetFPS)},
    {"SwapScreenBuffer", BIND_FN(SwapScreenBuffer)},
    {"PollInputEvents", BIND_FN(PollInputEvents)},
    {"WaitTime", BIND_FN(WaitTime)},
    {"SetRandomSeed", BIND_FN(SetRandomSeed)},
    {"GetRandomValue", BIND_FN(GetRandomValue)},
    {"TakeScreenshot", BIND_FN(TakeScreenshot)},
    {"SetConfigFlags", BIND_FN(SetConfigFlags)},
    {"OpenURL", BIND_FN(OpenURL)},
    {"SetTraceLogLevel", BIND_FN(SetTraceLogLevel)},
    {"SaveFileText", BIND_FN(SaveFileText)},
    {"FileRename", BIND_FN(FileRename)},
    {"FileRemove", BIND_FN(FileRemove)},
    {"FileCopy", BIND_FN(FileCopy)},
    {"FileMove", BIND_FN(FileMove)},
    {"FileTextReplace", BIND_FN(FileTextReplace)},
    {"FileTextFindIndex", BIND_FN(FileTextFindIndex)},
    {"FileExists", BIND_FN(FileExists)},
    {"DirectoryExists", BIND_FN(DirectoryExists)},
    {"IsFileExtension", BIND_FN(IsFileExtension)},
    {"GetFileLength", BIND_FN(GetFileLength)},
    {"GetFileModTime", BIND_FN(GetFileModTime)},
    {"GetFileExtension", BIND_FN(GetFileExtension)},
    {"GetFileName", BIND_FN(GetFileName)},
    {"GetFileNameWithoutExt", BIND_FN(GetFileNameWithoutExt)},
    {"GetDirectoryPath", BIND_FN(GetDirectoryPath)},
    {"GetPrevDirectoryPath", BIND_FN(GetPrevDirectoryPath)},
    {"GetWorkingDirectory", BIND_FN(GetWorkingDirectory)},
    {"GetApplicationDirectory", BIND_FN(GetApplicationDirectory)},
    {"MakeDirectory", BIND_FN(MakeDirectory)},
    {"ChangeDirectory", BIND_FN(ChangeDirectory)},
    {"IsPathFile", BIND_FN(IsPathFile)},
    {"IsFileNameValid", BIND_FN(IsFileNameValid)},
    {"LoadDirectoryFiles", BIND_FN(LoadDirectoryFiles)},
    {"LoadDirectoryFilesEx", BIND_FN(LoadDirectoryFilesEx)},
    {"UnloadDirectoryFiles", BIND_UNLOAD(UnloadDirectoryFiles)},
    {"IsFileDropped", BIND_FN(IsFileDropped)},
    {"LoadDroppedFiles", BIND_FN(LoadDroppedFiles)},
    {"UnloadDroppedFiles", BIND_UNLOAD(UnloadDroppedFiles)},
    {"GetDirectoryFileCount", BIND_FN(GetDirectoryFileCount)},
    {"GetDirectoryFileCountEx", BIND_FN(GetDirectoryFileCountEx)},
    {"LoadAutomationEventList", BIND_FN(LoadAutomationEventList)},
    {"UnloadAutomationEventList", BIND_UNLOAD(UnloadAutomationEventList)},
    {"ExportAutomationEventList", BIND_FN(ExportAutomationEventList)},
    {"SetAutomationEventBaseFrame", BIND_FN(SetAutomationEventBaseFrame)},
    {"StartAutomationEventRecording", BIND_FN(StartAutomationEventRecording)},
    {"StopAutomationEventRecording", BIND_FN(StopAutomationEventRecording)},
    {"PlayAutomationEvent", BIND_FN(PlayAutomationEvent)},
    {"IsKeyPressed", BIND_FN(IsKeyPressed)},
    {"IsKeyPressedRepeat", BIND_FN(IsKeyPressedRepeat)},
    {"IsKeyDown", BIND_FN(IsKeyDown)},
    {"IsKeyReleased", BIND_FN(IsKeyReleased)},
    {"IsKeyUp", BIND_FN(IsKeyUp)},
    {"GetKeyPressed", BIND_FN(GetKeyPressed)},
    {"GetCharPressed", BIND_FN(GetCharPressed)},
    {"GetKeyName", BIND_FN(GetKeyName)},
    {"SetExitKey", BIND_FN(SetExitKey)},
    {"IsGamepadAvailable", BIND_FN(IsGamepadAvailable)},
    {"GetGamepadName", BIND_FN(GetGamepadName)},
    {"IsGamepadButtonPressed", BIND_FN(IsGamepadButtonPressed)},
    {"IsGamepadButtonDown", BIND_FN(IsGamepadButtonDown)},
    {"IsGamepadButtonReleased", BIND_FN(IsGamepadButtonReleased)},
    {"IsGamepadButtonUp", BIND_FN(IsGamepadButtonUp)},
    {"GetGamepadButtonPressed", BIND_FN(GetGamepadButtonPressed)},
    {"GetGamepadAxisCount", BIND_FN(GetGamepadAxisCount)},
    {"GetGamepadAxisMovement", BIND_FN(GetGamepadAxisMovement)},
    {"SetGamepadMappings", BIND_FN(SetGamepadMappings)},
    {"SetGamepadVibration", BIND_FN(SetGamepadVibration)},
    {"IsMouseButtonPressed", BIND_FN(IsMouseButtonPressed)},
    {"IsMouseButtonDown", BIND_FN(IsMouseButtonDown)},
    {"IsMouseButtonReleased", BIND_FN(IsMouseButtonReleased)},
    {"IsMouseButtonUp", BIND_FN(IsMouseButtonUp)},
    {"GetMouseX", BIND_FN(GetMouseX)},
    {"GetMouseY", BIND_FN(GetMouseY)},
    {"GetMousePosition", BIND_FN(GetMousePosition)},
    {"GetMouseDelta", BIND_FN(GetMouseDelta)},
    {"SetMousePosition", BIND_FN(SetMousePosition)},
    {"SetMouseOffset", BIND_FN(SetMouseOffset)},
    {"SetMouseScale", BIND_FN(SetMouseScale)},
    {"GetMouseWheelMove", BIND_FN(GetMouseWheelMove)},
    {"GetMouseWheelMoveV", BIND_FN(GetMouseWheelMoveV)},
    {"SetMouseCursor", BIND_FN(SetMouseCursor)},
    {"GetTouchX", BIND_FN(GetTouchX)},
    {"GetTouchY", BIND_FN(GetTouchY)},
    {"GetTouchPosition", BIND_FN(GetTouchPosition)},
    {"GetTouchPointId", BIND_FN(GetTouchPointId)},
    {"GetTouchPointCount", BIND_FN(GetTouchPointCount)},
    {"SetGesturesEnabled", BIND_FN(SetGesturesEnabled)},
    {"IsGestureDetected", BIND_FN(IsGestureDetected)},
    {"GetGestureDetected", BIND_FN(GetGestureDetected)},
    {"GetGestureHoldDuration", BIND_FN(GetGestureHoldDuration)},
    {"GetGestureDragVector", BIND_FN(GetGestureDragVector)},
    {"GetGestureDragAngle", BIND_FN(GetGestureDragAngle)},
    {"GetGesturePinchVector", BIND_FN(GetGesturePinchVector)},
    {"GetGesturePinchAngle", BIND_FN(GetGesturePinchAngle)},
    {"UpdateCamera", BIND_FN(UpdateCamera)},
    {"UpdateCameraPro", BIND_FN(UpdateCameraPro)},
    {"SetShapesTexture", BIND_FN(SetShapesTexture)},
    {"GetShapesTexture", BIND_FN(GetShapesTexture)},
    {"GetShapesTextureRectangle", BIND_FN(GetShapesTextureRectangle)},
    {"DrawPixel", BIND_FN(DrawPixel)},
    {"DrawPixelV", BIND_FN(DrawPixelV)},
    {"DrawLine", BIND_FN(DrawLine)},
    {"DrawLineV", BIND_FN(DrawLineV)},
    {"DrawLineEx", BIND_FN(DrawLineEx)},
    {"DrawLineBezier", BIND_FN(DrawLineBezier)},
    {"DrawLineDashed", BIND_FN(DrawLineDashed)},
    {"DrawCircle", BIND_FN(DrawCircle)},
    {"DrawCircleV", BIND_FN(DrawCircleV)},
    {"DrawCircleGradient", BIND_FN(DrawCircleGradient)},
    {"DrawCircleSector", BIND_FN(DrawCircleSector)},
    {"DrawCircleSectorLines", BIND_FN(DrawCircleSectorLines)},
    {"DrawCircleLines", BIND_FN(DrawCircleLines)},
    {"DrawCircleLinesV", BIND_FN(DrawCircleLinesV)},
    {"DrawEllipse", BIND_FN(DrawEllipse)},
    {"DrawEllipseV", BIND_FN(DrawEllipseV)},
    {"DrawEllipseLines", BIND_FN(DrawEllipseLines)},
    {"DrawEllipseLinesV", BIND_FN(DrawEllipseLinesV)},
    {"DrawRing", BIND_FN(DrawRing)},
    {"DrawRingLines", BIND_FN(DrawRingLines)},
    {"DrawRectangle", BIND_FN(DrawRectangle)},
    {"DrawRectangleV", BIND_FN(DrawRectangleV)},
    {"DrawRectangleRec", BIND_FN(DrawRectangleRec)},
    {"DrawRectanglePro", BIND_FN(DrawRectanglePro)},
    {"DrawRectangleGradientV", BIND_FN(DrawRectangleGradientV)},
    {"DrawRectangleGradientH", BIND_FN(DrawRectangleGradientH)},
    {"DrawRectangleGradientEx", BIND_FN(DrawRectangleGradientEx)},
    {"DrawRectangleLines", BIND_FN(DrawRectangleLines)},
    {"DrawRectangleLinesEx", BIND_FN(DrawRectangleLinesEx)},
    {"DrawRectangleRounded", BIND_FN(DrawRectangleRounded)},
    {"DrawRectangleRoundedLines", BIND_FN(DrawRectangleRoundedLines)},
    {"DrawRectangleRoundedLinesEx", BIND_FN(DrawRectangleRoundedLinesEx)},
    {"DrawTriangle", BIND_FN(DrawTriangle)},
    {"DrawTriangleLines", BIND_FN(DrawTriangleLines)},
    {"DrawPoly", BIND_FN(DrawPoly)},
    {"DrawPolyLines", BIND_FN(DrawPolyLines)},
    {"DrawPolyLinesEx", BIND_FN(DrawPolyLinesEx)},
    {"DrawSplineSegmentLinear", BIND_FN(DrawSplineSegmentLinear)},
    {"DrawSplineSegmentBasis", BIND_FN(DrawSplineSegmentBasis)},
    {"DrawSplineSegmentCatmullRom", BIND_FN(DrawSplineSegmentCatmullRom)},
    {"DrawSplineSegmentBezierQuadratic", BIND_FN(DrawSplineSegmentBezierQuadratic)},
    {"DrawSplineSegmentBezierCubic", BIND_FN(DrawSplineSegmentBezierCubic)},
    {"GetSplinePointLinear", BIND_FN(GetSplinePointLinear)},
    {"GetSplinePointBasis", BIND_FN(GetSplinePointBasis)},
    {"GetSplinePointCatmullRom", BIND_FN(GetSplinePointCatmullRom)},
    {"GetSplinePointBezierQuad", BIND_FN(GetSplinePointBezierQuad)},
    {"GetSplinePointBezierCubic", BIND_FN(GetSplinePointBezierCubic)},
    {"CheckCollisionRecs", BIND_FN(CheckCollisionRecs)},
    {"CheckCollisionCircles", BIND_FN(CheckCollisionCircles)},
    {"CheckCollisionCircleRec", BIND_FN(CheckCollisionCircleRec)},
    {"CheckCollisionCircleLine", BIND_FN(CheckCollisionCircleLine)},
    {"CheckCollisionPointRec", BIND_FN(CheckCollisionPointRec)},
    {"CheckCollisionPointCircle", BIND_FN(CheckCollisionPointCircle)},
    {"CheckCollisionPointTriangle", BIND_FN(CheckCollisionPointTriangle)},
    {"CheckCollisionPointLine", BIND_FN(CheckCollisionPointLine)},
    {"GetCollisionRec", BIND_FN(GetCollisionRec)},
    {"LoadImage", BIND_FN(LoadImage)},
    {"LoadImageRaw", BIND_FN(LoadImageRaw)},
    {"LoadImageFromTexture", BIND_FN(LoadImageFromTexture)},
    {"LoadImageFromScreen", BIND_FN(LoadImageFromScreen)},
    {"IsImageValid", BIND_FN(IsImageValid)},
    {"UnloadImage", BIND_UNLOAD(UnloadImage)},
    {"ExportImage", BIND_FN(ExportImage)},
    {"ExportImageAsCode", BIND_FN(ExportImageAsCode)},
    {"GenImageColor", BIND_FN(GenImageColor)},
    {"GenImageGradientLinear", BIND_FN(GenImageGradientLinear)},
    {"GenImageGradientRadial", BIND_FN(GenImageGradientRadial)},
    {"GenImageGradientSquare", BIND_FN(GenImageGradientSquare)},
    {"GenImageChecked", BIND_FN(GenImageChecked)},
    {"GenImageWhiteNoise", BIND_FN(GenImageWhiteNoise)},
    {"GenImagePerlinNoise", BIND_FN(GenImagePerlinNoise)},
    {"GenImageCellular", BIND_FN(GenImageCellular)},
    {"GenImageText", BIND_FN(GenImageText)},
    {"ImageCopy", BIND_FN(ImageCopy)},
    {"ImageFromImage", BIND_FN(ImageFromImage)},
    {"ImageFromChannel", BIND_FN(ImageFromChannel)},
    {"ImageText", BIND_FN(ImageText)},
    {"ImageTextEx", BIND_FN(ImageTextEx)},
    {"ImageFormat", BIND_FN(ImageFormat)},
    {"ImageToPOT", BIND_FN(ImageToPOT)},
    {"ImageCrop", BIND_FN(ImageCrop)},
    {"ImageAlphaCrop", BIND_FN(ImageAlphaCrop)},
    {"ImageAlphaClear", BIND_FN(ImageAlphaClear)},
    {"ImageAlphaMask", BIND_FN(ImageAlphaMask)},
    {"ImageAlphaPremultiply", BIND_FN(ImageAlphaPremultiply)},
    {"ImageBlurGaussian", BIND_FN(ImageBlurGaussian)},
    {"ImageResize", BIND_FN(ImageResize)},
    {"ImageResizeNN", BIND_FN(ImageResizeNN)},
    {"ImageResizeCanvas", BIND_FN(ImageResizeCanvas)},
    {"ImageMipmaps", BIND_FN(ImageMipmaps)},
    {"ImageDither", BIND_FN(ImageDither)},
    {"ImageFlipVertical", BIND_FN(ImageFlipVertical)},
    {"ImageFlipHorizontal", BIND_FN(ImageFlipHorizontal)},
    {"ImageRotate", BIND_FN(ImageRotate)},
    {"ImageRotateCW", BIND_FN(ImageRotateCW)},
    {"ImageRotateCCW", BIND_FN(ImageRotateCCW)},
    {"ImageColorTint", BIND_FN(ImageColorTint)},
    {"ImageColorInvert", BIND_FN(ImageColorInvert)},
    {"ImageColorGrayscale", BIND_FN(ImageColorGrayscale)},
    {"ImageColorContrast", BIND_FN(ImageColorContrast)},
    {"ImageColorBrightness", BIND_FN(ImageColorBrightness)},
    {"ImageColorReplace", BIND_FN(ImageColorReplace)},
    {"GetImageAlphaBorder", BIND_FN(GetImageAlphaBorder)},
    {"GetImageColor", BIND_FN(GetImageColor)},
    {"ImageClearBackground", BIND_FN(ImageClearBackground)},
    {"ImageDrawPixel", BIND_FN(ImageDrawPixel)},
    {"ImageDrawPixelV", BIND_FN(ImageDrawPixelV)},
    {"ImageDrawLine", BIND_FN(ImageDrawLine)},
    {"ImageDrawLineV", BIND_FN(ImageDrawLineV)},
    {"ImageDrawLineEx", BIND_FN(ImageDrawLineEx)},
    {"ImageDrawCircle", BIND_FN(ImageDrawCircle)},
    {"ImageDrawCircleV", BIND_FN(ImageDrawCircleV)},
    {"ImageDrawCircleLines", BIND_FN(ImageDrawCircleLines)},
    {"ImageDrawCircleLinesV", BIND_FN(ImageDrawCircleLinesV)},
    {"ImageDrawRectangle", BIND_FN(ImageDrawRectangle)},
    {"ImageDrawRectangleV", BIND_FN(ImageDrawRectangleV)},
    {"ImageDrawRectangleRec", BIND_FN(ImageDrawRectangleRec)},
    {"ImageDrawRectangleLines", BIND_FN(ImageDrawRectangleLines)},
    {"ImageDrawTriangle", BIND_FN(ImageDrawTriangle)},
    {"ImageDrawTriangleEx", BIND_FN(ImageDrawTriangleEx)},
    {"ImageDrawTriangleLines", BIND_FN(ImageDrawTriangleLines)},
    {"ImageDraw", BIND_FN(ImageDraw)},
    {"ImageDrawText", BIND_FN(ImageDrawText)},
    {"ImageDrawTextEx", BIND_FN(ImageDrawTextEx)},
    {"LoadTexture", BIND_FN(LoadTexture)},
    {"LoadTextureFromImage", BIND_FN(LoadTextureFromImage)},
    {"LoadTextureCubemap", BIND_FN(LoadTextureCubemap)},
    {"LoadRenderTexture", BIND_FN(LoadRenderTexture)},
    {"IsTextureValid", BIND_FN(IsTextureValid)},
    {"UnloadTexture", BIND_UNLOAD(UnloadTexture)},
    {"IsRenderTextureValid", BIND_FN(IsRenderTextureValid)},
    {"UnloadRenderTexture", BIND_UNLOAD(UnloadRenderTexture)},
    {"GenTextureMipmaps", BIND_FN(GenTextureMipmaps)},
    {"SetTextureFilter", BIND_FN(SetTextureFilter)},
    {"SetTextureWrap", BIND_FN(SetTextureWrap)},
    {"DrawTexture", BIND_FN(DrawTexture)},
    {"DrawTextureV", BIND_FN(DrawTextureV)},
    {"DrawTextureEx", BIND_FN(DrawTextureEx)},
    {"DrawTextureRec", BIND_FN(DrawTextureRec)},
    {"DrawTexturePro", BIND_FN(DrawTexturePro)},
    {"DrawTextureNPatch", BIND_FN(DrawTextureNPatch)},
    {"ColorIsEqual", BIND_FN(ColorIsEqual)},
    {"Fade", BIND_FN(Fade)},
    {"ColorToInt", BIND_FN(ColorToInt)},
    {"ColorNormalize", BIND_FN(ColorNormalize)},
    {"ColorFromNormalized", BIND_FN(ColorFromNormalized)},
    {"ColorToHSV", BIND_FN(ColorToHSV)},
    {"ColorFromHSV", BIND_FN(ColorFromHSV)},
    {"ColorTint", BIND_FN(ColorTint)},
    {"ColorBrightness", BIND_FN(ColorBrightness)},
    {"ColorContrast", BIND_FN(ColorContrast)},
    {"ColorAlpha", BIND_FN(ColorAlpha)},
    {"ColorAlphaBlend", BIND_FN(ColorAlphaBlend)},
    {"ColorLerp", BIND_FN(ColorLerp)},
    {"GetColor", BIND_FN(GetColor)},
    {"GetPixelDataSize", BIND_FN(GetPixelDataSize)},
    {"GetFontDefault", BIND_FN(GetFontDefault)},
    {"LoadFont", BIND_FN(LoadFont)},
    {"LoadFontFromImage", BIND_FN(LoadFontFromImage)},
    {"IsFontValid", BIND_FN(IsFontValid)},
    {"UnloadFont", BIND_UNLOAD(UnloadFont)},
    {"ExportFontAsCode", BIND_FN(ExportFontAsCode)},
    {"DrawFPS", BIND_FN(DrawFPS)},
    {"DrawText", BIND_FN(DrawText)},
    {"DrawTextEx", BIND_FN(DrawTextEx)},
    {"DrawTextPro", BIND_FN(DrawTextPro)},
    {"DrawTextCodepoint", BIND_FN(DrawTextCodepoint)},
    {"SetTextLineSpacing", BIND_FN(SetTextLineSpacing)},
    {"MeasureText", BIND_FN(MeasureText)},
    {"MeasureTextEx", BIND_FN(MeasureTextEx)},
    {"GetGlyphIndex", BIND_FN(GetGlyphIndex)},
    {"GetGlyphInfo", BIND_FN(GetGlyphInfo)},
    {"GetGlyphAtlasRec", BIND_FN(GetGlyphAtlasRec)},
    {"GetCodepointCount", BIND_FN(GetCodepointCount)},
    {"TextIsEqual", BIND_FN(TextIsEqual)},
    {"TextLength", BIND_FN(TextLength)},
    {"TextSubtext", BIND_FN(TextSubtext)},
    {"TextRemoveSpaces", BIND_FN(TextRemoveSpaces)},
    {"TextFindIndex", BIND_FN(TextFindIndex)},
    {"TextToInteger", BIND_FN(TextToInteger)},
    {"TextToFloat", BIND_FN(TextToFloat)},
    {"DrawLine3D", BIND_FN(DrawLine3D)},
    {"DrawPoint3D", BIND_FN(DrawPoint3D)},
    {"DrawCircle3D", BIND_FN(DrawCircle3D)},
    {"DrawTriangle3D", BIND_FN(DrawTriangle3D)},
    {"DrawCube", BIND_FN(DrawCube)},
    {"DrawCubeV", BIND_FN(DrawCubeV)},
    {"DrawCubeWires", BIND_FN(DrawCubeWires)},
    {"DrawCubeWiresV", BIND_FN(DrawCubeWiresV)},
    {"DrawSphere", BIND_FN(DrawSphere)},
    {"DrawSphereEx", BIND_FN(DrawSphereEx)},
    {"DrawSphereWires", BIND_FN(DrawSphereWires)},
    {"DrawCylinder", BIND_FN(DrawCylinder)},
    {"DrawCylinderEx", BIND_FN(DrawCylinderEx)},
    {"DrawCylinderWires", BIND_FN(DrawCylinderWires)},
    {"DrawCylinderWiresEx", BIND_FN(DrawCylinderWiresEx)},
    {"DrawCapsule", BIND_FN(DrawCapsule)},
    {"DrawCapsuleWires", BIND_FN(DrawCapsuleWires)},
    {"DrawPlane", BIND_FN(DrawPlane)},
    {"DrawRay", BIND_FN(DrawRay)},
    {"DrawGrid", BIND_FN(DrawGrid)},
    {"LoadModel", BIND_FN(LoadModel)},
    {"IsModelValid", BIND_FN(IsModelValid)},
    {"UnloadModel", BIND_UNLOAD(UnloadModel)},
    {"GetModelBoundingBox", BIND_FN(GetModelBoundingBox)},
    {"DrawModel", BIND_FN(DrawModel)},
    {"DrawModelEx", BIND_FN(DrawModelEx)},
    {"DrawModelWires", BIND_FN(DrawModelWires)},
    {"DrawModelWiresEx", BIND_FN(DrawModelWiresEx)},
    {"DrawBoundingBox", BIND_FN(DrawBoundingBox)},
    {"DrawBillboard", BIND_FN(DrawBillboard)},
    {"DrawBillboardRec", BIND_FN(DrawBillboardRec)},
    {"DrawBillboardPro", BIND_FN(DrawBillboardPro)},
    {"UploadMesh", BIND_FN(UploadMesh)},
    {"UnloadMesh", BIND_UNLOAD(UnloadMesh)},
    {"DrawMesh", BIND_FN(DrawMesh)},
    {"GetMeshBoundingBox", BIND_FN(GetMeshBoundingBox)},
    {"GenMeshTangents", BIND_FN(GenMeshTangents)},
    {"ExportMesh", BIND_FN(ExportMesh)},
    {"ExportMeshAsCode", BIND_FN(ExportMeshAsCode)},
    {"GenMeshPoly", BIND_FN(GenMeshPoly)},
    {"GenMeshPlane", BIND_FN(GenMeshPlane)},
    {"GenMeshCube", BIND_FN(GenMeshCube)},
    {"GenMeshSphere", BIND_FN(GenMeshSphere)},
    {"GenMeshHemiSphere", BIND_FN(GenMeshHemiSphere)},
    {"GenMeshCylinder", BIND_FN(GenMeshCylinder)},
    {"GenMeshCone", BIND_FN(GenMeshCone)},
    {"GenMeshTorus", BIND_FN(GenMeshTorus)},
    {"GenMeshKnot", BIND_FN(GenMeshKnot)},
    {"GenMeshHeightmap", BIND_FN(GenMeshHeightmap)},
    {"GenMeshCubicmap", BIND_FN(GenMeshCubicmap)},
    {"LoadMaterialDefault", BIND_FN(LoadMaterialDefault)},
    {"IsMaterialValid", BIND_FN(IsMaterialValid)},
    {"UnloadMaterial", BIND_UNLOAD(UnloadMaterial)},
    {"SetMaterialTexture", BIND_FN(SetMaterialTexture)},
    {"SetModelMeshMaterial", BIND_FN(SetModelMeshMaterial)},
    {"UpdateModelAnimation", BIND_FN(UpdateModelAnimation)},
    {"UpdateModelAnimationEx", BIND_FN(UpdateModelAnimationEx)},
    {"IsModelAnimationValid", BIND_FN(IsModelAnimationValid)},
    {"CheckCollisionSpheres", BIND_FN(CheckCollisionSpheres)},
    {"CheckCollisionBoxes", BIND_FN(CheckCollisionBoxes)},
    {"CheckCollisionBoxSphere", BIND_FN(CheckCollisionBoxSphere)},
    {"GetRayCollisionSphere", BIND_FN(GetRayCollisionSphere)},
    {"GetRayCollisionBox", BIND_FN(GetRayCollisionBox)},
    {"GetRayCollisionMesh", BIND_FN(GetRayCollisionMesh)},
    {"GetRayCollisionTriangle", BIND_FN(GetRayCollisionTriangle)},
    {"GetRayCollisionQuad", BIND_FN(GetRayCollisionQuad)},
    {"InitAudioDevice", BIND_FN(InitAudioDevice)},
    {"CloseAudioDevice", BIND_FN(CloseAudioDevice)},
    {"IsAudioDeviceReady", BIND_FN(IsAudioDeviceReady)},
    {"SetMasterVolume", BIND_FN(SetMasterVolume)},
    {"GetMasterVolume", BIND_FN(GetMasterVolume)},
    {"LoadWave", BIND_FN(LoadWave)},
    {"IsWaveValid", BIND_FN(IsWaveValid)},
    {"LoadSound", BIND_FN(LoadSound)},
    {"LoadSoundFromWave", BIND_FN(LoadSoundFromWave)},
    {"IsSoundValid", BIND_FN(IsSoundValid)},
    {"UnloadWave", BIND_UNLOAD(UnloadWave)},
    {"UnloadSound", BIND_UNLOAD(UnloadSound)},
    {"ExportWave", BIND_FN(ExportWave)},
    {"ExportWaveAsCode", BIND_FN(ExportWaveAsCode)},
    {"PlaySound", BIND_FN(PlaySound)},
    {"StopSound", BIND_FN(StopSound)},
    {"PauseSound", BIND_FN(PauseSound)},
    {"ResumeSound", BIND_FN(ResumeSound)},
    {"IsSoundPlaying", BIND_FN(IsSoundPlaying)},
    {"SetSoundVolume", BIND_FN(SetSoundVolume)},
    {"SetSoundPitch", BIND_FN(SetSoundPitch)},
    {"SetSoundPan", BIND_FN(SetSoundPan)},
    {"WaveCopy", BIND_FN(WaveCopy)},
    {"WaveCrop", BIND_FN(WaveCrop)},
    {"WaveFormat", BIND_FN(WaveFormat)},
    {"LoadMusicStream", BIND_FN(LoadMusicStream)},
    {"IsMusicValid", BIND_FN(IsMusicValid)},
    {"UnloadMusicStream", BIND_UNLOAD(UnloadMusicStream)},
    {"PlayMusicStream", BIND_FN(PlayMusicStream)},
    {"IsMusicStreamPlaying", BIND_FN(IsMusicStreamPlaying)},
    {"UpdateMusicStream", BIND_FN(UpdateMusicStream)},
    {"StopMusicStream", BIND_FN(StopMusicStream)},
    {"PauseMusicStream", BIND_FN(PauseMusicStream)},
    {"ResumeMusicStream", BIND_FN(ResumeMusicStream)},
    {"SeekMusicStream", BIND_FN(SeekMusicStream)},
    {"SetMusicVolume", BIND_FN(SetMusicVolume)},
    {"SetMusicPitch", BIND_FN(SetMusicPitch)},
    {"SetMusicPan", BIND_FN(SetMusicPan)},
    {"GetMusicTimeLength", BIND_FN(GetMusicTimeLength)},
    {"GetMusicTimePlayed", BIND_FN(GetMusicTimePlayed)},
    {"LoadAudioStream", BIND_FN(LoadAudioStream)},
    {"IsAudioStreamValid", BIND_FN(IsAudioStreamValid)},
    {"UnloadAudioStream", BIND_UNLOAD(UnloadAudioStream)},
    {"IsAudioStreamProcessed", BIND_FN(IsAudioStreamProcessed)},
    {"PlayAudioStream", BIND_FN(PlayAudioStream)},
    {"PauseAudioStream", BIND_FN(PauseAudioStream)},
    {"ResumeAudioStream", BIND_FN(ResumeAudioStream)},
    {"IsAudioStreamPlaying", BIND_FN(IsAudioStreamPlaying)},
    {"StopAudioStream", BIND_FN(StopAudioStream)},
    {"SetAudioStreamVolume", BIND_FN(SetAudioStreamVolume)},
    {"SetAudioStreamPitch", BIND_FN(SetAudioStreamPitch)},
    {"SetAudioStreamPan", BIND_FN(SetAudioStreamPan)},
    {"SetAudioStreamBufferSizeDefault", BIND_FN(SetAudioStreamBufferSizeDefault)},
};

// constructors take the struct fields in declaration order, missing ones stay zero
const FnDef kConstructors[] = {
    {"Vector2", bind::CtorVector2},
    {"Vector3", bind::CtorVector3},
    {"Color", bind::CtorColor},
    {"Vector4", &bind::Ctor<Vector4, &Vector4::x, &Vector4::y, &Vector4::z, &Vector4::w>::Call},
    {"Matrix", &bind::Ctor<Matrix, &Matrix::m0, &Matrix::m4, &Matrix::m8, &Matrix::m12, &Matrix::m1, &Matrix::m5, &Matrix::m9, &Matrix::m13, &Matrix::m2, &Matrix::m6, &Matrix::m10, &Matrix::m14, &Matrix::m3, &Matrix::m7, &Matrix::m11, &Matrix::m15>::Call},
    {"Rectangle", &bind::Ctor<Rectangle, &Rectangle::x, &Rectangle::y, &Rectangle::width, &Rectangle::height>::Call},
    {"Texture", &bind::Ctor<Texture, &Texture::id, &Texture::width, &Texture::height, &Texture::mipmaps, &Texture::format>::Call},
    {"RenderTexture", &bind::Ctor<RenderTexture, &RenderTexture::id, &RenderTexture::texture, &RenderTexture::depth>::Call},
    {"NPatchInfo", &bind::Ctor<NPatchInfo, &NPatchInfo::source, &NPatchInfo::left, &NPatchInfo::top, &NPatchInfo::right, &NPatchInfo::bottom, &NPatchInfo::layout>::Call},
    {"Camera3D", &bind::Ctor<Camera3D, &Camera3D::position, &Camera3D::target, &Camera3D::up, &Camera3D::fovy, &Camera3D::projection>::Call},
    {"Camera2D", &bind::Ctor<Camera2D, &Camera2D::offset, &Camera2D::target, &Camera2D::rotation, &Camera2D::zoom>::Call},
    {"MaterialMap", &bind::Ctor<MaterialMap, &MaterialMap::texture, &MaterialMap::color, &MaterialMap::value>::Call},
    {"Transform", &bind::Ctor<Transform, &Transform::translation, &Transform::rotation, &Transform::scale>::Call},
    {"BoneInfo", &bind::Ctor<BoneInfo, &BoneInfo::parent>::Call},
    {"Ray", &bind::Ctor<Ray, &Ray::position, &Ray::direction>::Call},
    {"RayCollision", &bind::Ctor<RayCollision, &RayCollision::hit, &RayCollision::distance, &RayCollision::point, &RayCollision::normal>::Call},
    {"BoundingBox", &bind::Ctor<BoundingBox, &BoundingBox::min, &BoundingBox::max>::Call},
    {"VrDeviceInfo", &bind::Ctor<VrDeviceInfo, &VrDeviceInfo::hResolution, &VrDeviceInfo::vResolution, &VrDeviceInfo::hScreenSize, &VrDeviceInfo::vScreenSize, &VrDeviceInfo::eyeToScreenDistance, &VrDeviceInfo::lensSeparationDistance, &VrDeviceInfo::interpupillaryDistance>::Call},
    {"AutomationEvent", &bind::Ctor<AutomationEvent, &AutomationEvent::frame, &AutomationEvent::type>::Call},
};

struct NumDef {
    const char *name;
    double value;
};

const NumDef kConstants[] = {
    {"FLAG_VSYNC_HINT", 64.0},  // Set to try enabling V-Sync on GPU
    {"FLAG_FULLSCREEN_MODE", 2.0},  // Set to run program in fullscreen
    {"FLAG_WINDOW_RESIZABLE", 4.0},  // Set to allow resizable window
    {"FLAG_WINDOW_UNDECORATED", 8.0},  // Set to disable window decoration (frame and buttons)
    {"FLAG_WINDOW_HIDDEN", 128.0},  // Set to hide window
    {"FLAG_WINDOW_MINIMIZED", 512.0},  // Set to minimize window (iconify)
    {"FLAG_WINDOW_MAXIMIZED", 1024.0},  // Set to maximize window (expanded to monitor)
    {"FLAG_WINDOW_UNFOCUSED", 2048.0},  // Set to window non focused
    {"FLAG_WINDOW_TOPMOST", 4096.0},  // Set to window always on top
    {"FLAG_WINDOW_ALWAYS_RUN", 256.0},  // Set to allow windows running while minimized
    {"FLAG_WINDOW_TRANSPARENT", 16.0},  // Set to allow transparent framebuffer
    {"FLAG_WINDOW_HIGHDPI", 8192.0},  // Set to support HighDPI
    {"FLAG_WINDOW_MOUSE_PASSTHROUGH", 16384.0},  // Set to support mouse passthrough, only supported when FLAG_WINDOW_UNDECORATED
    {"FLAG_BORDERLESS_WINDOWED_MODE", 32768.0},  // Set to run program in borderless windowed mode
    {"FLAG_MSAA_4X_HINT", 32.0},  // Set to try enabling MSAA 4X
    {"FLAG_INTERLACED_HINT", 65536.0},  // Set to try enabling interlaced video format (for V3D)
    {"LOG_ALL", 0.0},  // Display all logs
    {"LOG_TRACE", 1.0},  // Trace logging, intended for internal use only
    {"LOG_DEBUG", 2.0},  // Debug logging, used for internal debugging, it should be disabled on release builds
    {"LOG_INFO", 3.0},  // Info logging, used for program execution info
    {"LOG_WARNING", 4.0},  // Warning logging, used on recoverable failures
    {"LOG_ERROR", 5.0},  // Error logging, used on unrecoverable failures
    {"LOG_FATAL", 6.0},  // Fatal logging, used to abort program: exit(EXIT_FAILURE)
    {"LOG_NONE", 7.0},  // Disable logging
    {"KEY_NULL", 0.0},  // Key: NULL, used for no key pressed
    {"KEY_APOSTROPHE", 39.0},  // Key: '
    {"KEY_COMMA", 44.0},  // Key: ,
    {"KEY_MINUS", 45.0},  // Key: -
    {"KEY_PERIOD", 46.0},  // Key: .
    {"KEY_SLASH", 47.0},  // Key: /
    {"KEY_ZERO", 48.0},  // Key: 0
    {"KEY_ONE", 49.0},  // Key: 1
    {"KEY_TWO", 50.0},  // Key: 2
    {"KEY_THREE", 51.0},  // Key: 3
    {"KEY_FOUR", 52.0},  // Key: 4
    {"KEY_FIVE", 53.0},  // Key: 5
    {"KEY_SIX", 54.0},  // Key: 6
    {"KEY_SEVEN", 55.0},  // Key: 7
    {"KEY_EIGHT", 56.0},  // Key: 8
    {"KEY_NINE", 57.0},  // Key: 9
    {"KEY_SEMICOLON", 59.0},  // Key: ;
    {"KEY_EQUAL", 61.0},  // Key: =
    {"KEY_A", 65.0},  // Key: A | a
    {"KEY_B", 66.0},  // Key: B | b
    {"KEY_C", 67.0},  // Key: C | c
    {"KEY_D", 68.0},  // Key: D | d
    {"KEY_E", 69.0},  // Key: E | e
    {"KEY_F", 70.0},  // Key: F | f
    {"KEY_G", 71.0},  // Key: G | g
    {"KEY_H", 72.0},  // Key: H | h
    {"KEY_I", 73.0},  // Key: I | i
    {"KEY_J", 74.0},  // Key: J | j
    {"KEY_K", 75.0},  // Key: K | k
    {"KEY_L", 76.0},  // Key: L | l
    {"KEY_M", 77.0},  // Key: M | m
    {"KEY_N", 78.0},  // Key: N | n
    {"KEY_O", 79.0},  // Key: O | o
    {"KEY_P", 80.0},  // Key: P | p
    {"KEY_Q", 81.0},  // Key: Q | q
    {"KEY_R", 82.0},  // Key: R | r
    {"KEY_S", 83.0},  // Key: S | s
    {"KEY_T", 84.0},  // Key: T | t
    {"KEY_U", 85.0},  // Key: U | u
    {"KEY_V", 86.0},  // Key: V | v
    {"KEY_W", 87.0},  // Key: W | w
    {"KEY_X", 88.0},  // Key: X | x
    {"KEY_Y", 89.0},  // Key: Y | y
    {"KEY_Z", 90.0},  // Key: Z | z
    {"KEY_LEFT_BRACKET", 91.0},  // Key: [
    {"KEY_BACKSLASH", 92.0},  // Key: '\'
    {"KEY_RIGHT_BRACKET", 93.0},  // Key: ]
    {"KEY_GRAVE", 96.0},  // Key: `
    {"KEY_SPACE", 32.0},  // Key: Space
    {"KEY_ESCAPE", 256.0},  // Key: Esc
    {"KEY_ENTER", 257.0},  // Key: Enter
    {"KEY_TAB", 258.0},  // Key: Tab
    {"KEY_BACKSPACE", 259.0},  // Key: Backspace
    {"KEY_INSERT", 260.0},  // Key: Ins
    {"KEY_DELETE", 261.0},  // Key: Del
    {"KEY_RIGHT", 262.0},  // Key: Cursor right
    {"KEY_LEFT", 263.0},  // Key: Cursor left
    {"KEY_DOWN", 264.0},  // Key: Cursor down
    {"KEY_UP", 265.0},  // Key: Cursor up
    {"KEY_PAGE_UP", 266.0},  // Key: Page up
    {"KEY_PAGE_DOWN", 267.0},  // Key: Page down
    {"KEY_HOME", 268.0},  // Key: Home
    {"KEY_END", 269.0},  // Key: End
    {"KEY_CAPS_LOCK", 280.0},  // Key: Caps lock
    {"KEY_SCROLL_LOCK", 281.0},  // Key: Scroll down
    {"KEY_NUM_LOCK", 282.0},  // Key: Num lock
    {"KEY_PRINT_SCREEN", 283.0},  // Key: Print screen
    {"KEY_PAUSE", 284.0},  // Key: Pause
    {"KEY_F1", 290.0},  // Key: F1
    {"KEY_F2", 291.0},  // Key: F2
    {"KEY_F3", 292.0},  // Key: F3
    {"KEY_F4", 293.0},  // Key: F4
    {"KEY_F5", 294.0},  // Key: F5
    {"KEY_F6", 295.0},  // Key: F6
    {"KEY_F7", 296.0},  // Key: F7
    {"KEY_F8", 297.0},  // Key: F8
    {"KEY_F9", 298.0},  // Key: F9
    {"KEY_F10", 299.0},  // Key: F10
    {"KEY_F11", 300.0},  // Key: F11
    {"KEY_F12", 301.0},  // Key: F12
    {"KEY_LEFT_SHIFT", 340.0},  // Key: Shift left
    {"KEY_LEFT_CONTROL", 341.0},  // Key: Control left
    {"KEY_LEFT_ALT", 342.0},  // Key: Alt left
    {"KEY_LEFT_SUPER", 343.0},  // Key: Super left
    {"KEY_RIGHT_SHIFT", 344.0},  // Key: Shift right
    {"KEY_RIGHT_CONTROL", 345.0},  // Key: Control right
    {"KEY_RIGHT_ALT", 346.0},  // Key: Alt right
    {"KEY_RIGHT_SUPER", 347.0},  // Key: Super right
    {"KEY_KB_MENU", 348.0},  // Key: KB menu
    {"KEY_KP_0", 320.0},  // Key: Keypad 0
    {"KEY_KP_1", 321.0},  // Key: Keypad 1
    {"KEY_KP_2", 322.0},  // Key: Keypad 2
    {"KEY_KP_3", 323.0},  // Key: Keypad 3
    {"KEY_KP_4", 324.0},  // Key: Keypad 4
    {"KEY_KP_5", 325.0},  // Key: Keypad 5
    {"KEY_KP_6", 326.0},  // Key: Keypad 6
    {"KEY_KP_7", 327.0},  // Key: Keypad 7
    {"KEY_KP_8", 328.0},  // Key: Keypad 8
    {"KEY_KP_9", 329.0},  // Key: Keypad 9
    {"KEY_KP_DECIMAL", 330.0},  // Key: Keypad .
    {"KEY_KP_DIVIDE", 331.0},  // Key: Keypad /
    {"KEY_KP_MULTIPLY", 332.0},  // Key: Keypad *
    {"KEY_KP_SUBTRACT", 333.0},  // Key: Keypad -
    {"KEY_KP_ADD", 334.0},  // Key: Keypad +
    {"KEY_KP_ENTER", 335.0},  // Key: Keypad Enter
    {"KEY_KP_EQUAL", 336.0},  // Key: Keypad =
    {"KEY_BACK", 4.0},  // Key: Android back button
    {"KEY_MENU", 5.0},  // Key: Android menu button
    {"KEY_VOLUME_UP", 24.0},  // Key: Android volume up button
    {"KEY_VOLUME_DOWN", 25.0},  // Key: Android volume down button
    {"MOUSE_BUTTON_LEFT", 0.0},  // Mouse button left
    {"MOUSE_BUTTON_RIGHT", 1.0},  // Mouse button right
    {"MOUSE_BUTTON_MIDDLE", 2.0},  // Mouse button middle (pressed wheel)
    {"MOUSE_BUTTON_SIDE", 3.0},  // Mouse button side (advanced mouse device)
    {"MOUSE_BUTTON_EXTRA", 4.0},  // Mouse button extra (advanced mouse device)
    {"MOUSE_BUTTON_FORWARD", 5.0},  // Mouse button forward (advanced mouse device)
    {"MOUSE_BUTTON_BACK", 6.0},  // Mouse button back (advanced mouse device)
    {"MOUSE_CURSOR_DEFAULT", 0.0},  // Default pointer shape
    {"MOUSE_CURSOR_ARROW", 1.0},  // Arrow shape
    {"MOUSE_CURSOR_IBEAM", 2.0},  // Text writing cursor shape
    {"MOUSE_CURSOR_CROSSHAIR", 3.0},  // Cross shape
    {"MOUSE_CURSOR_POINTING_HAND", 4.0},  // Pointing hand cursor
    {"MOUSE_CURSOR_RESIZE_EW", 5.0},  // Horizontal resize/move arrow shape
    {"MOUSE_CURSOR_RESIZE_NS", 6.0},  // Vertical resize/move arrow shape
    {"MOUSE_CURSOR_RESIZE_NWSE", 7.0},  // Top-left to bottom-right diagonal resize/move arrow shape
    {"MOUSE_CURSOR_RESIZE_NESW", 8.0},  // The top-right to bottom-left diagonal resize/move arrow shape
    {"MOUSE_CURSOR_RESIZE_ALL", 9.0},  // The omnidirectional resize/move cursor shape
    {"MOUSE_CURSOR_NOT_ALLOWED", 10.0},  // The operation-not-allowed shape
    {"GAMEPAD_BUTTON_UNKNOWN", 0.0},  // Unknown button, for error checking
    {"GAMEPAD_BUTTON_LEFT_FACE_UP", 1.0},  // Gamepad left DPAD up button
    {"GAMEPAD_BUTTON_LEFT_FACE_RIGHT", 2.0},  // Gamepad left DPAD right button
    {"GAMEPAD_BUTTON_LEFT_FACE_DOWN", 3.0},  // Gamepad left DPAD down button
    {"GAMEPAD_BUTTON_LEFT_FACE_LEFT", 4.0},  // Gamepad left DPAD left button
    {"GAMEPAD_BUTTON_RIGHT_FACE_UP", 5.0},  // Gamepad right button up (i.e. PS3: Triangle, Xbox: Y)
    {"GAMEPAD_BUTTON_RIGHT_FACE_RIGHT", 6.0},  // Gamepad right button right (i.e. PS3: Circle, Xbox: B)
    {"GAMEPAD_BUTTON_RIGHT_FACE_DOWN", 7.0},  // Gamepad right button down (i.e. PS3: Cross, Xbox: A)
    {"GAMEPAD_BUTTON_RIGHT_FACE_LEFT", 8.0},  // Gamepad right button left (i.e. PS3: Square, Xbox: X)
    {"GAMEPAD_BUTTON_LEFT_TRIGGER_1", 9.0},  // Gamepad top/back trigger left (first), it could be a trailing button
    {"GAMEPAD_BUTTON_LEFT_TRIGGER_2", 10.0},  // Gamepad top/back trigger left (second), it could be a trailing button
    {"GAMEPAD_BUTTON_RIGHT_TRIGGER_1", 11.0},  // Gamepad top/back trigger right (first), it could be a trailing button
    {"GAMEPAD_BUTTON_RIGHT_TRIGGER_2", 12.0},  // Gamepad top/back trigger right (second), it could be a trailing button
    {"GAMEPAD_BUTTON_MIDDLE_LEFT", 13.0},  // Gamepad center buttons, left one (i.e. PS3: Select)
    {"GAMEPAD_BUTTON_MIDDLE", 14.0},  // Gamepad center buttons, middle one (i.e. PS3: PS, Xbox: XBOX)
    {"GAMEPAD_BUTTON_MIDDLE_RIGHT", 15.0},  // Gamepad center buttons, right one (i.e. PS3: Start)
    {"GAMEPAD_BUTTON_LEFT_THUMB", 16.0},  // Gamepad joystick pressed button left
    {"GAMEPAD_BUTTON_RIGHT_THUMB", 17.0},  // Gamepad joystick pressed button right
    {"GAMEPAD_AXIS_LEFT_X", 0.0},  // Gamepad left stick X axis
    {"GAMEPAD_AXIS_LEFT_Y", 1.0},  // Gamepad left stick Y axis
    {"GAMEPAD_AXIS_RIGHT_X", 2.0},  // Gamepad right stick X axis
    {"GAMEPAD_AXIS_RIGHT_Y", 3.0},  // Gamepad right stick Y axis
    {"GAMEPAD_AXIS_LEFT_TRIGGER", 4.0},  // Gamepad back trigger left, pressure level: [1..-1]
    {"GAMEPAD_AXIS_RIGHT_TRIGGER", 5.0},  // Gamepad back trigger right, pressure level: [1..-1]
    {"MATERIAL_MAP_ALBEDO", 0.0},  // Albedo material (same as: MATERIAL_MAP_DIFFUSE)
    {"MATERIAL_MAP_METALNESS", 1.0},  // Metalness material (same as: MATERIAL_MAP_SPECULAR)
    {"MATERIAL_MAP_NORMAL", 2.0},  // Normal material
    {"MATERIAL_MAP_ROUGHNESS", 3.0},  // Roughness material
    {"MATERIAL_MAP_OCCLUSION", 4.0},  // Ambient occlusion material
    {"MATERIAL_MAP_EMISSION", 5.0},  // Emission material
    {"MATERIAL_MAP_HEIGHT", 6.0},  // Heightmap material
    {"MATERIAL_MAP_CUBEMAP", 7.0},  // Cubemap material (NOTE: Uses GL_TEXTURE_CUBE_MAP)
    {"MATERIAL_MAP_IRRADIANCE", 8.0},  // Irradiance material (NOTE: Uses GL_TEXTURE_CUBE_MAP)
    {"MATERIAL_MAP_PREFILTER", 9.0},  // Prefilter material (NOTE: Uses GL_TEXTURE_CUBE_MAP)
    {"MATERIAL_MAP_BRDF", 10.0},  // Brdf material
    {"SHADER_LOC_VERTEX_POSITION", 0.0},  // Shader location: vertex attribute: position
    {"SHADER_LOC_VERTEX_TEXCOORD01", 1.0},  // Shader location: vertex attribute: texcoord01
    {"SHADER_LOC_VERTEX_TEXCOORD02", 2.0},  // Shader location: vertex attribute: texcoord02
    {"SHADER_LOC_VERTEX_NORMAL", 3.0},  // Shader location: vertex attribute: normal
    {"SHADER_LOC_VERTEX_TANGENT", 4.0},  // Shader location: vertex attribute: tangent
    {"SHADER_LOC_VERTEX_COLOR", 5.0},  // Shader location: vertex attribute: color
    {"SHADER_LOC_MATRIX_MVP", 6.0},  // Shader location: matrix uniform: model-view-projection
    {"SHADER_LOC_MATRIX_VIEW", 7.0},  // Shader location: matrix uniform: view (camera transform)
    {"SHADER_LOC_MATRIX_PROJECTION", 8.0},  // Shader location: matrix uniform: projection
    {"SHADER_LOC_MATRIX_MODEL", 9.0},  // Shader location: matrix uniform: model (transform)
    {"SHADER_LOC_MATRIX_NORMAL", 10.0},  // Shader location: matrix uniform: normal
    {"SHADER_LOC_VECTOR_VIEW", 11.0},  // Shader location: vector uniform: view
    {"SHADER_LOC_COLOR_DIFFUSE", 12.0},  // Shader location: vector uniform: diffuse color
    {"SHADER_LOC_COLOR_SPECULAR", 13.0},  // Shader location: vector uniform: specular color
    {"SHADER_LOC_COLOR_AMBIENT", 14.0},  // Shader location: vector uniform: ambient color
    {"SHADER_LOC_MAP_ALBEDO", 15.0},  // Shader location: sampler2d texture: albedo (same as: SHADER_LOC_MAP_DIFFUSE)
    {"SHADER_LOC_MAP_METALNESS", 16.0},  // Shader location: sampler2d texture: metalness (same as: SHADER_LOC_MAP_SPECULAR)
    {"SHADER_LOC_MAP_NORMAL", 17.0},  // Shader location: sampler2d texture: normal
    {"SHADER_LOC_MAP_ROUGHNESS", 18.0},  // Shader location: sampler2d texture: roughness
    {"SHADER_LOC_MAP_OCCLUSION", 19.0},  // Shader location: sampler2d texture: occlusion
    {"SHADER_LOC_MAP_EMISSION", 20.0},  // Shader location: sampler2d texture: emission
    {"SHADER_LOC_MAP_HEIGHT", 21.0},  // Shader location: sampler2d texture: heightmap
    {"SHADER_LOC_MAP_CUBEMAP", 22.0},  // Shader location: samplerCube texture: cubemap
    {"SHADER_LOC_MAP_IRRADIANCE", 23.0},  // Shader location: samplerCube texture: irradiance
    {"SHADER_LOC_MAP_PREFILTER", 24.0},  // Shader location: samplerCube texture: prefilter
    {"SHADER_LOC_MAP_BRDF", 25.0},  // Shader location: sampler2d texture: brdf
    {"SHADER_LOC_VERTEX_BONEIDS", 26.0},  // Shader location: vertex attribute: bone indices
    {"SHADER_LOC_VERTEX_BONEWEIGHTS", 27.0},  // Shader location: vertex attribute: bone weights
    {"SHADER_LOC_MATRIX_BONETRANSFORMS", 28.0},  // Shader location: matrix attribute: bone transforms (animation)
    {"SHADER_LOC_VERTEX_INSTANCETRANSFORM", 29.0},  // Shader location: vertex attribute: instance transforms
    {"SHADER_UNIFORM_FLOAT", 0.0},  // Shader uniform type: float
    {"SHADER_UNIFORM_VEC2", 1.0},  // Shader uniform type: vec2 (2 float)
    {"SHADER_UNIFORM_VEC3", 2.0},  // Shader uniform type: vec3 (3 float)
    {"SHADER_UNIFORM_VEC4", 3.0},  // Shader uniform type: vec4 (4 float)
    {"SHADER_UNIFORM_INT", 4.0},  // Shader uniform type: int
    {"SHADER_UNIFORM_IVEC2", 5.0},  // Shader uniform type: ivec2 (2 int)
    {"SHADER_UNIFORM_IVEC3", 6.0},  // Shader uniform type: ivec3 (3 int)
    {"SHADER_UNIFORM_IVEC4", 7.0},  // Shader uniform type: ivec4 (4 int)
    {"SHADER_UNIFORM_UINT", 8.0},  // Shader uniform type: unsigned int
    {"SHADER_UNIFORM_UIVEC2", 9.0},  // Shader uniform type: uivec2 (2 unsigned int)
    {"SHADER_UNIFORM_UIVEC3", 10.0},  // Shader uniform type: uivec3 (3 unsigned int)
    {"SHADER_UNIFORM_UIVEC4", 11.0},  // Shader uniform type: uivec4 (4 unsigned int)
    {"SHADER_UNIFORM_SAMPLER2D", 12.0},  // Shader uniform type: sampler2d
    {"SHADER_ATTRIB_FLOAT", 0.0},  // Shader attribute type: float
    {"SHADER_ATTRIB_VEC2", 1.0},  // Shader attribute type: vec2 (2 float)
    {"SHADER_ATTRIB_VEC3", 2.0},  // Shader attribute type: vec3 (3 float)
    {"SHADER_ATTRIB_VEC4", 3.0},  // Shader attribute type: vec4 (4 float)
    {"PIXELFORMAT_UNCOMPRESSED_GRAYSCALE", 1.0},  // 8 bit per pixel (no alpha)
    {"PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA", 2.0},  // 8*2 bpp (2 channels)
    {"PIXELFORMAT_UNCOMPRESSED_R5G6B5", 3.0},  // 16 bpp
    {"PIXELFORMAT_UNCOMPRESSED_R8G8B8", 4.0},  // 24 bpp
    {"PIXELFORMAT_UNCOMPRESSED_R5G5B5A1", 5.0},  // 16 bpp (1 bit alpha)
    {"PIXELFORMAT_UNCOMPRESSED_R4G4B4A4", 6.0},  // 16 bpp (4 bit alpha)
    {"PIXELFORMAT_UNCOMPRESSED_R8G8B8A8", 7.0},  // 32 bpp
    {"PIXELFORMAT_UNCOMPRESSED_R32", 8.0},  // 32 bpp (1 channel - float)
    {"PIXELFORMAT_UNCOMPRESSED_R32G32B32", 9.0},  // 32*3 bpp (3 channels - float)
    {"PIXELFORMAT_UNCOMPRESSED_R32G32B32A32", 10.0},  // 32*4 bpp (4 channels - float)
    {"PIXELFORMAT_UNCOMPRESSED_R16", 11.0},  // 16 bpp (1 channel - half float)
    {"PIXELFORMAT_UNCOMPRESSED_R16G16B16", 12.0},  // 16*3 bpp (3 channels - half float)
    {"PIXELFORMAT_UNCOMPRESSED_R16G16B16A16", 13.0},  // 16*4 bpp (4 channels - half float)
    {"PIXELFORMAT_COMPRESSED_DXT1_RGB", 14.0},  // 4 bpp (no alpha)
    {"PIXELFORMAT_COMPRESSED_DXT1_RGBA", 15.0},  // 4 bpp (1 bit alpha)
    {"PIXELFORMAT_COMPRESSED_DXT3_RGBA", 16.0},  // 8 bpp
    {"PIXELFORMAT_COMPRESSED_DXT5_RGBA", 17.0},  // 8 bpp
    {"PIXELFORMAT_COMPRESSED_ETC1_RGB", 18.0},  // 4 bpp
    {"PIXELFORMAT_COMPRESSED_ETC2_RGB", 19.0},  // 4 bpp
    {"PIXELFORMAT_COMPRESSED_ETC2_EAC_RGBA", 20.0},  // 8 bpp
    {"PIXELFORMAT_COMPRESSED_PVRT_RGB", 21.0},  // 4 bpp
    {"PIXELFORMAT_COMPRESSED_PVRT_RGBA", 22.0},  // 4 bpp
    {"PIXELFORMAT_COMPRESSED_ASTC_4x4_RGBA", 23.0},  // 8 bpp
    {"PIXELFORMAT_COMPRESSED_ASTC_8x8_RGBA", 24.0},  // 2 bpp
    {"TEXTURE_FILTER_POINT", 0.0},  // No filter, pixel approximation
    {"TEXTURE_FILTER_BILINEAR", 1.0},  // Linear filtering
    {"TEXTURE_FILTER_TRILINEAR", 2.0},  // Trilinear filtering (linear with mipmaps)
    {"TEXTURE_FILTER_ANISOTROPIC_4X", 3.0},  // Anisotropic filtering 4x
    {"TEXTURE_FILTER_ANISOTROPIC_8X", 4.0},  // Anisotropic filtering 8x
    {"TEXTURE_FILTER_ANISOTROPIC_16X", 5.0},  // Anisotropic filtering 16x
    {"TEXTURE_WRAP_REPEAT", 0.0},  // Repeats texture in tiled mode
    {"TEXTURE_WRAP_CLAMP", 1.0},  // Clamps texture to edge pixel in tiled mode
    {"TEXTURE_WRAP_MIRROR_REPEAT", 2.0},  // Mirrors and repeats the texture in tiled mode
    {"TEXTURE_WRAP_MIRROR_CLAMP", 3.0},  // Mirrors and clamps to border the texture in tiled mode
    {"CUBEMAP_LAYOUT_AUTO_DETECT", 0.0},  // Automatically detect layout type
    {"CUBEMAP_LAYOUT_LINE_VERTICAL", 1.0},  // Layout is defined by a vertical line with faces
    {"CUBEMAP_LAYOUT_LINE_HORIZONTAL", 2.0},  // Layout is defined by a horizontal line with faces
    {"CUBEMAP_LAYOUT_CROSS_THREE_BY_FOUR", 3.0},  // Layout is defined by a 3x4 cross with cubemap faces
    {"CUBEMAP_LAYOUT_CROSS_FOUR_BY_THREE", 4.0},  // Layout is defined by a 4x3 cross with cubemap faces
    {"FONT_DEFAULT", 0.0},  // Default font generation, anti-aliased
    {"FONT_BITMAP", 1.0},  // Bitmap font generation, no anti-aliasing
    {"FONT_SDF", 2.0},  // SDF font generation, requires external shader
    {"BLEND_ALPHA", 0.0},  // Blend textures considering alpha (default)
    {"BLEND_ADDITIVE", 1.0},  // Blend textures adding colors
    {"BLEND_MULTIPLIED", 2.0},  // Blend textures multiplying colors
    {"BLEND_ADD_COLORS", 3.0},  // Blend textures adding colors (alternative)
    {"BLEND_SUBTRACT_COLORS", 4.0},  // Blend textures subtracting colors (alternative)
    {"BLEND_ALPHA_PREMULTIPLY", 5.0},  // Blend premultiplied textures considering alpha
    {"BLEND_CUSTOM", 6.0},  // Blend textures using custom src/dst factors (use rlSetBlendFactors())
    {"BLEND_CUSTOM_SEPARATE", 7.0},  // Blend textures using custom rgb/alpha separate src/dst factors (use rlSetBlendFactorsSeparate())
    {"GESTURE_NONE", 0.0},  // No gesture
    {"GESTURE_TAP", 1.0},  // Tap gesture
    {"GESTURE_DOUBLETAP", 2.0},  // Double tap gesture
    {"GESTURE_HOLD", 4.0},  // Hold gesture
    {"GESTURE_DRAG", 8.0},  // Drag gesture
    {"GESTURE_SWIPE_RIGHT", 16.0},  // Swipe right gesture
    {"GESTURE_SWIPE_LEFT", 32.0},  // Swipe left gesture
    {"GESTURE_SWIPE_UP", 64.0},  // Swipe up gesture
    {"GESTURE_SWIPE_DOWN", 128.0},  // Swipe down gesture
    {"GESTURE_PINCH_IN", 256.0},  // Pinch in gesture
    {"GESTURE_PINCH_OUT", 512.0},  // Pinch out gesture
    {"CAMERA_CUSTOM", 0.0},  // Camera custom, controlled by user (UpdateCamera() does nothing)
    {"CAMERA_FREE", 1.0},  // Camera free mode
    {"CAMERA_ORBITAL", 2.0},  // Camera orbital, around target, zoom supported
    {"CAMERA_FIRST_PERSON", 3.0},  // Camera first person
    {"CAMERA_THIRD_PERSON", 4.0},  // Camera third person
    {"CAMERA_PERSPECTIVE", 0.0},  // Perspective projection
    {"CAMERA_ORTHOGRAPHIC", 1.0},  // Orthographic projection
    {"NPATCH_NINE_PATCH", 0.0},  // Npatch layout: 3x3 tiles
    {"NPATCH_THREE_PATCH_VERTICAL", 1.0},  // Npatch layout: 1x3 tiles
    {"NPATCH_THREE_PATCH_HORIZONTAL", 2.0},  // Npatch layout: 3x1 tiles
    {"RAYLIB_VERSION_MAJOR", 6.0},  // 
    {"RAYLIB_VERSION_MINOR", 0.0},  // 
    {"RAYLIB_VERSION_PATCH", 0.0},  // 
    {"PI", 3.141592653589793},  // 
    {"DEG2RAD", 0.017453292519943295},  // 
    {"RAD2DEG", 57.29577951308232},  // 
    {"LIGHTGRAY", 3368601855.0},  // Light Gray
    {"GRAY", 2189591295.0},  // Gray
    {"DARKGRAY", 1347440895.0},  // Dark Gray
    {"YELLOW", 4260954367.0},  // Yellow
    {"GOLD", 4291494143.0},  // Gold
    {"ORANGE", 4288741631.0},  // Orange
    {"PINK", 4285383423.0},  // Pink
    {"RED", 3861460991.0},  // Red
    {"MAROON", 3189848063.0},  // Maroon
    {"GREEN", 14954751.0},  // Green
    {"LIME", 10366975.0},  // Lime
    {"DARKGREEN", 7679231.0},  // Dark Green
    {"SKYBLUE", 1723858943.0},  // Sky Blue
    {"BLUE", 7991807.0},  // Blue
    {"DARKBLUE", 5418239.0},  // Dark Blue
    {"PURPLE", 3363504127.0},  // Purple
    {"VIOLET", 2268905215.0},  // Violet
    {"DARKPURPLE", 1881112319.0},  // Dark Purple
    {"BEIGE", 3551560703.0},  // Beige
    {"BROWN", 2137673727.0},  // Brown
    {"DARKBROWN", 1279209471.0},  // Dark Brown
    {"WHITE", 4294967295.0},  // White
    {"BLACK", 255.0},  // Black
    {"BLANK", 0.0},  // Blank (Transparent)
    {"MAGENTA", 4278255615.0},  // Magenta
    {"RAYWHITE", 4126537215.0},  // My own White (raylib logo)
};

}  // namespace

const char *const kRaylibUserdataTypes[] = {
    "Vector4",
    "Matrix",
    "Rectangle",
    "Image",
    "Texture",
    "RenderTexture",
    "NPatchInfo",
    "GlyphInfo",
    "Font",
    "Camera3D",
    "Camera2D",
    "Mesh",
    "Shader",
    "MaterialMap",
    "Material",
    "Transform",
    "BoneInfo",
    "ModelSkeleton",
    "Model",
    "ModelAnimation",
    "Ray",
    "RayCollision",
    "BoundingBox",
    "Wave",
    "AudioStream",
    "Sound",
    "Music",
    "VrDeviceInfo",
    "VrStereoConfig",
    "FilePathList",
    "AutomationEvent",
    "AutomationEventList",
    nullptr,
};

void OpenRaylib(lua_State *L) {
    for (const TypeInfo *type : kTypes)
        bind::RegisterType(L, *type);

    lua_createtable(L, 0, 828 + 35);
    for (const FnDef &def : kFunctions) {
        lua_pushcfunction(L, def.fn, def.name);
        lua_rawsetfield(L, -2, def.name);
    }
    for (const FnDef &def : kConstructors) {
        lua_pushcfunction(L, def.fn, def.name);
        lua_rawsetfield(L, -2, def.name);
    }
    for (const NumDef &def : kConstants) {
        lua_pushnumber(L, def.value);
        lua_rawsetfield(L, -2, def.name);
    }
    lua_setglobal(L, "raylib");
}

// ---------------------------------------------------------------------------
// Not bound: 109 of 600 raylib functions.
//
// Each needs an adapter in src/rl_adapters.hpp that owns the lifetime the C
// signature leaves implicit. Until one exists the function is absent rather
// than exposed as a raw address.
//
//   SetWindowIcons              Image * array
//   GetWindowHandle             returns void *, ownership is not described by the api
//   SetShaderValue              raw const void * buffer parameter
//   SetShaderValueV             raw const void * buffer parameter
//   LoadRandomSequence          returns int *, ownership is not described by the api
//   UnloadRandomSequence        int * out parameter
//   TraceLog                    variadic, use string.format
//   SetTraceLogCallback         takes the C callback TraceLogCallback
//   MemAlloc                    returns void *, ownership is not described by the api
//   MemRealloc                  returns void *, ownership is not described by the api
//   MemFree                     raw void * buffer parameter
//   LoadFileData                host provides this through the vfs
//   UnloadFileData              host provides this through the vfs
//   SaveFileData                raw void * buffer parameter
//   ExportDataAsCode            const unsigned char * array
//   LoadFileText                host provides this through the vfs
//   UnloadFileText              host provides this through the vfs
//   SetLoadFileDataCallback     takes the C callback LoadFileDataCallback
//   SetSaveFileDataCallback     takes the C callback SaveFileDataCallback
//   SetLoadFileTextCallback     takes the C callback LoadFileTextCallback
//   SetSaveFileTextCallback     takes the C callback SaveFileTextCallback
//   CompressData                returns unsigned char *, ownership is not described by the api
//   DecompressData              returns unsigned char *, ownership is not described by the api
//   EncodeDataBase64            returns char *, ownership is not described by the api
//   DecodeDataBase64            returns unsigned char *, ownership is not described by the api
//   ComputeCRC32                unsigned char * out parameter
//   ComputeMD5                  returns unsigned int *, ownership is not described by the api
//   ComputeSHA1                 returns unsigned int *, ownership is not described by the api
//   ComputeSHA256               returns unsigned int *, ownership is not described by the api
//   SetAutomationEventList      raylib keeps the pointer past the call
//   DrawLineStrip               const Vector2 * array
//   DrawTriangleFan             const Vector2 * array
//   DrawTriangleStrip           const Vector2 * array
//   DrawSplineLinear            const Vector2 * array
//   DrawSplineBasis             const Vector2 * array
//   DrawSplineCatmullRom        const Vector2 * array
//   DrawSplineBezierQuadratic   const Vector2 * array
//   DrawSplineBezierCubic       const Vector2 * array
//   CheckCollisionPointPoly     const Vector2 * array
//   CheckCollisionLines         Vector2 * out parameter
//   LoadImageAnim               int * out parameter
//   LoadImageAnimFromMemory     const unsigned char * array
//   LoadImageFromMemory         const unsigned char * array
//   ExportImageToMemory         returns unsigned char *, ownership is not described by the api
//   ImageKernelConvolution      const float * array
//   LoadImageColors             returns Color *, ownership is not described by the api
//   LoadImagePalette            returns Color *, ownership is not described by the api
//   UnloadImageColors           Color * out parameter
//   UnloadImagePalette          Color * out parameter
//   ImageDrawTriangleFan        const Vector2 * array
//   ImageDrawTriangleStrip      const Vector2 * array
//   UpdateTexture               raw const void * buffer parameter
//   UpdateTextureRec            raw const void * buffer parameter
//   GetPixelColor               raw void * buffer parameter
//   SetPixelColor               raw void * buffer parameter
//   LoadFontEx                  const int * array
//   LoadFontFromMemory          const unsigned char * array
//   LoadFontData                returns GlyphInfo *, ownership is not described by the api
//   GenImageFontAtlas           const GlyphInfo * array
//   UnloadFontData              GlyphInfo * array
//   DrawTextCodepoints          const int * array
//   MeasureTextCodepoints       const int * array
//   LoadUTF8                    returns char *, ownership is not described by the api
//   UnloadUTF8                  raw char * buffer parameter
//   LoadCodepoints              returns int *, ownership is not described by the api
//   UnloadCodepoints            int * out parameter
//   GetCodepoint                int * out parameter
//   GetCodepointNext            int * out parameter
//   GetCodepointPrevious        int * out parameter
//   CodepointToUTF8             int * out parameter
//   LoadTextLines               returns char **, ownership is not described by the api
//   UnloadTextLines             raw char ** buffer parameter
//   TextCopy                    raw char * buffer parameter
//   TextFormat                  variadic, use string.format
//   GetTextBetween              returns char *, ownership is not described by the api
//   TextReplace                 returns char *, ownership is not described by the api
//   TextReplaceAlloc            returns char *, ownership is not described by the api
//   TextReplaceBetween          returns char *, ownership is not described by the api
//   TextReplaceBetweenAlloc     returns char *, ownership is not described by the api
//   TextInsert                  returns char *, ownership is not described by the api
//   TextInsertAlloc             returns char *, ownership is not described by the api
//   TextJoin                    returns char *, ownership is not described by the api
//   TextSplit                   returns char **, ownership is not described by the api
//   TextAppend                  raw char * buffer parameter
//   TextToUpper                 returns char *, ownership is not described by the api
//   TextToLower                 returns char *, ownership is not described by the api
//   TextToPascal                returns char *, ownership is not described by the api
//   TextToSnake                 returns char *, ownership is not described by the api
//   TextToCamel                 returns char *, ownership is not described by the api
//   DrawTriangleStrip3D         const Vector3 * array
//   LoadModelFromMesh           takes ownership of its argument's buffers
//   UpdateMeshBuffer            raw const void * buffer parameter
//   DrawMeshInstanced           const Matrix * array
//   LoadMaterials               returns Material *, ownership is not described by the api
//   LoadModelAnimations         returns ModelAnimation *, ownership is not described by the api
//   UnloadModelAnimations       ModelAnimation * array
//   LoadWaveFromMemory          const unsigned char * array
//   LoadSoundAlias              returns a handle borrowing another handle's allocation
//   UpdateSound                 raw const void * buffer parameter
//   UnloadSoundAlias            consumes a handle borrowing another handle's allocation
//   LoadWaveSamples             returns float *, ownership is not described by the api
//   UnloadWaveSamples           float * out parameter
//   LoadMusicStreamFromMemory   const unsigned char * array
//   UpdateAudioStream           raw const void * buffer parameter
//   SetAudioStreamCallback      takes the C callback AudioCallback
//   AttachAudioStreamProcessor  takes the C callback AudioCallback
//   DetachAudioStreamProcessor  takes the C callback AudioCallback
//   AttachAudioMixedProcessor   takes the C callback AudioCallback
//   DetachAudioMixedProcessor   takes the C callback AudioCallback
